package main

import (
	"strings"
	"testing"
)

// TestClassify covers the HTTP-method → mutating mapping. The rules:
//
//	GET, HEAD, OPTIONS → false
//	anything else      → true
//
// Method is case-insensitive (OAS spec uses lowercase).
func TestClassify(t *testing.T) {
	cases := []struct {
		method string
		want   bool
	}{
		{"get", false},
		{"GET", false},
		{"head", false},
		{"options", false},
		{"post", true},
		{"PUT", true},
		{"patch", true},
		{"delete", true},
	}
	for _, c := range cases {
		t.Run(c.method, func(t *testing.T) {
			if got := classify(c.method); got != c.want {
				t.Fatalf("classify(%q) = %v, want %v", c.method, got, c.want)
			}
		})
	}
}

// TestRenderSorts keys alphabetically and emits the canonical
// `mutating.gen.go` shape.
func TestRenderSorts(t *testing.T) {
	entries := map[string]bool{
		"invoices_create": true,
		"companies_list":  false,
		"contacts_get":    false,
	}
	got := render(entries)
	if !strings.Contains(got, `"companies_list":`) {
		t.Fatalf("missing companies_list entry: %s", got)
	}
	if !strings.Contains(got, `"invoices_create":`) {
		t.Fatalf("missing invoices_create entry: %s", got)
	}
	// Sort check: "companies_list" must appear before "invoices_create".
	if strings.Index(got, "companies_list") > strings.Index(got, "invoices_create") {
		t.Fatalf("entries not sorted: %s", got)
	}
	// Header sanity.
	if !strings.HasPrefix(got, "// Code generated by fiken-mutating-gen; DO NOT EDIT.\n") {
		t.Fatalf("missing DO NOT EDIT header: %s", got)
	}
}
