// Command fiken-mutating-gen reads api/fiken-openapi.yaml and writes
// ops/mutating.gen.go: a `package ops` file containing a single
// map[string]bool keyed by operationId in snake_case form.
//
// The mapping rule is purely HTTP-method based: GET/HEAD/OPTIONS map
// to `false` (non-mutating); anything else maps to `true`.
package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	defaultSpec   = "api/fiken-openapi.yaml"
	defaultOutput = "ops/mutating.gen.go"
)

func main() {
	specPath := flag.String("spec", defaultSpec, "path to the OAS YAML")
	outPath := flag.String("out", defaultOutput, "output file")
	flag.Parse()

	if err := run(*specPath, *outPath); err != nil {
		fmt.Fprintf(os.Stderr, "fiken-mutating-gen: %v\n", err)
		os.Exit(1)
	}
}

func run(specPath, outPath string) error {
	data, err := os.ReadFile(specPath)
	if err != nil {
		return fmt.Errorf("read spec: %w", err)
	}
	entries, err := parseEntries(data)
	if err != nil {
		return err
	}
	body := render(entries)

	if err := os.MkdirAll(parentDir(outPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(outPath, []byte(body), 0o644)
}

// classify returns true if the HTTP method mutates state.
func classify(method string) bool {
	switch strings.ToUpper(method) {
	case "GET", "HEAD", "OPTIONS":
		return false
	default:
		return true
	}
}

// httpMethods is the set of OAS path-item method keys. The other keys
// at the path-item level (parameters, summary, description, servers,
// $ref) are not operations and must be skipped.
var httpMethods = map[string]struct{}{
	"get":     {},
	"put":     {},
	"post":    {},
	"delete":  {},
	"options": {},
	"head":    {},
	"patch":   {},
	"trace":   {},
}

// parseEntries walks paths.*.{get,post,…}.operationId and emits one
// map entry per operation, key = snake_case(operationId), value =
// classify(method).
func parseEntries(specYAML []byte) (map[string]bool, error) {
	var root struct {
		Paths map[string]map[string]yaml.Node `yaml:"paths"`
	}
	if err := yaml.Unmarshal(specYAML, &root); err != nil {
		return nil, fmt.Errorf("unmarshal spec: %w", err)
	}
	out := make(map[string]bool, 128)
	for _, ops := range root.Paths {
		for key, node := range ops {
			if _, ok := httpMethods[strings.ToLower(key)]; !ok {
				continue
			}
			var op struct {
				OperationID string `yaml:"operationId"`
			}
			if err := node.Decode(&op); err != nil {
				return nil, fmt.Errorf("decode operation %s: %w", key, err)
			}
			if op.OperationID == "" {
				continue
			}
			out[snake(op.OperationID)] = classify(key)
		}
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("no operationIds found — wrong spec file?")
	}
	return out, nil
}

// snake converts e.g. "getCompanies" → "get_companies" and
// "createSalesV2" → "create_sales_v2".
func snake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			b.WriteByte('_')
		}
		if r >= 'A' && r <= 'Z' {
			r += 'a' - 'A'
		}
		b.WriteRune(r)
	}
	return b.String()
}

// render emits the generated Go file. Entries are sorted by key for
// stability so `codegen-clean` doesn't fire spuriously.
func render(entries map[string]bool) string {
	keys := make([]string, 0, len(entries))
	for k := range entries {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	maxLen := 0
	for _, k := range keys {
		if len(k) > maxLen {
			maxLen = len(k)
		}
	}

	var b strings.Builder
	b.WriteString("// Code generated by fiken-mutating-gen; DO NOT EDIT.\n\n")
	b.WriteString("package ops\n\n")
	b.WriteString("// mutating maps operation id (snake_case) to whether the underlying\n")
	b.WriteString("// HTTP method mutates server state. Source: api/fiken-openapi.yaml.\n")
	b.WriteString("var mutating = map[string]bool{\n")
	for _, k := range keys {
		pad := strings.Repeat(" ", maxLen-len(k))
		fmt.Fprintf(&b, "\t%q:%s %v,\n", k, pad, entries[k])
	}
	b.WriteString("}\n\n")
	b.WriteString("// IsMutating reports whether op mutates state. Unknown ops are\n")
	b.WriteString("// treated as mutating (fail-closed for read-only mode).\n")
	b.WriteString("func IsMutating(op string) bool {\n")
	b.WriteString("\tif v, ok := mutating[op]; ok {\n")
	b.WriteString("\t\treturn v\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn true\n")
	b.WriteString("}\n")
	return b.String()
}

func parentDir(p string) string {
	for i := len(p) - 1; i >= 0; i-- {
		if p[i] == '/' {
			return p[:i]
		}
	}
	return "."
}
