// Code generated by ogen, DO NOT EDIT.

package fiken

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AddAttachmentToContact implements addAttachmentToContact operation.
	//
	// Creates and adds a new attachment/document to a contact.
	//
	// POST /companies/{companySlug}/contacts/{contactId}/attachments
	AddAttachmentToContact(ctx context.Context, req OptAddAttachmentToContactReq, params AddAttachmentToContactParams) (*AddAttachmentToContactCreated, error)
	// AddAttachmentToCreditNoteDraft implements addAttachmentToCreditNoteDraft operation.
	//
	// Creates and adds a new attachment to a credit note draft.
	//
	// POST /companies/{companySlug}/creditNotes/drafts/{draftId}/attachments
	AddAttachmentToCreditNoteDraft(ctx context.Context, req OptAddAttachmentToCreditNoteDraftReq, params AddAttachmentToCreditNoteDraftParams) (*AddAttachmentToCreditNoteDraftCreated, error)
	// AddAttachmentToInvoice implements addAttachmentToInvoice operation.
	//
	// Creates and adds a new attachment to an Invoice.
	//
	// POST /companies/{companySlug}/invoices/{invoiceId}/attachments
	AddAttachmentToInvoice(ctx context.Context, req OptAddAttachmentToInvoiceReq, params AddAttachmentToInvoiceParams) (*AddAttachmentToInvoiceCreated, error)
	// AddAttachmentToInvoiceDraft implements addAttachmentToInvoiceDraft operation.
	//
	// Creates and adds a new attachment to an invoice draft.
	//
	// POST /companies/{companySlug}/invoices/drafts/{draftId}/attachments
	AddAttachmentToInvoiceDraft(ctx context.Context, req OptAddAttachmentToInvoiceDraftReq, params AddAttachmentToInvoiceDraftParams) (*AddAttachmentToInvoiceDraftCreated, error)
	// AddAttachmentToJournalEntry implements addAttachmentToJournalEntry operation.
	//
	// Creates and adds a new attachment to a Journal Entry.
	//
	// POST /companies/{companySlug}/journalEntries/{journalEntryId}/attachments
	AddAttachmentToJournalEntry(ctx context.Context, req OptAddAttachmentToJournalEntryReq, params AddAttachmentToJournalEntryParams) (*AddAttachmentToJournalEntryCreated, error)
	// AddAttachmentToOfferDraft implements addAttachmentToOfferDraft operation.
	//
	// Creates and adds a new attachment to an offer draft.
	//
	// POST /companies/{companySlug}/offers/drafts/{draftId}/attachments
	AddAttachmentToOfferDraft(ctx context.Context, req OptAddAttachmentToOfferDraftReq, params AddAttachmentToOfferDraftParams) (*AddAttachmentToOfferDraftCreated, error)
	// AddAttachmentToOrderConfirmationDraft implements addAttachmentToOrderConfirmationDraft operation.
	//
	// Creates and adds a new attachment to an order confirmation draft.
	//
	// POST /companies/{companySlug}/orderConfirmations/drafts/{draftId}/attachments
	AddAttachmentToOrderConfirmationDraft(ctx context.Context, req OptAddAttachmentToOrderConfirmationDraftReq, params AddAttachmentToOrderConfirmationDraftParams) (*AddAttachmentToOrderConfirmationDraftCreated, error)
	// AddAttachmentToPurchase implements addAttachmentToPurchase operation.
	//
	// Creates and adds a new attachment to a Purchase.
	//
	// POST /companies/{companySlug}/purchases/{purchaseId}/attachments
	AddAttachmentToPurchase(ctx context.Context, req OptAddAttachmentToPurchaseReq, params AddAttachmentToPurchaseParams) (*AddAttachmentToPurchaseCreated, error)
	// AddAttachmentToPurchaseDraft implements addAttachmentToPurchaseDraft operation.
	//
	// Creates and adds a new attachment to a draft.
	//
	// POST /companies/{companySlug}/purchases/drafts/{draftId}/attachments
	AddAttachmentToPurchaseDraft(ctx context.Context, req OptAddAttachmentToPurchaseDraftReq, params AddAttachmentToPurchaseDraftParams) (*AddAttachmentToPurchaseDraftCreated, error)
	// AddAttachmentToSale implements addAttachmentToSale operation.
	//
	// Creates and adds a new attachment to a Sale.
	//
	// POST /companies/{companySlug}/sales/{saleId}/attachments
	AddAttachmentToSale(ctx context.Context, req OptAddAttachmentToSaleReq, params AddAttachmentToSaleParams) (*AddAttachmentToSaleCreated, error)
	// AddAttachmentToSaleDraft implements addAttachmentToSaleDraft operation.
	//
	// Creates and adds a new attachment to a draft.
	//
	// POST /companies/{companySlug}/sales/drafts/{draftId}/attachments
	AddAttachmentToSaleDraft(ctx context.Context, req OptAddAttachmentToSaleDraftReq, params AddAttachmentToSaleDraftParams) (*AddAttachmentToSaleDraftCreated, error)
	// AddContactPersonToContact implements addContactPersonToContact operation.
	//
	// Adds a new contact person to a contact.
	//
	// POST /companies/{companySlug}/contacts/{contactId}/contactPerson
	AddContactPersonToContact(ctx context.Context, req *ContactPerson, params AddContactPersonToContactParams) (*AddContactPersonToContactOK, error)
	// CreateActivity implements createActivity operation.
	//
	// Creates a new activity.
	//
	// POST /companies/{companySlug}/activities
	CreateActivity(ctx context.Context, req *ActivityRequest, params CreateActivityParams) (*CreateActivityCreated, error)
	// CreateBankAccount implements createBankAccount operation.
	//
	// Creates a new bank account. The Location response header returns the URL of the newly created bank
	// account.
	// Possible types of bank accounts are NORMAL, TAX_DEDUCTION, FOREIGN, and CREDIT_CARD. The field
	// "foreignService" should only be filled out for accounts of type FOREIGN.
	//
	// POST /companies/{companySlug}/bankAccounts
	CreateBankAccount(ctx context.Context, req *BankAccountRequest, params CreateBankAccountParams) (*CreateBankAccountCreated, error)
	// CreateContact implements createContact operation.
	//
	// Creates a new contact. The Location response header returns the URL of the newly created contact.
	//
	// POST /companies/{companySlug}/contacts
	CreateContact(ctx context.Context, req *Contact, params CreateContactParams) (*CreateContactCreated, error)
	// CreateCreditNoteCounter implements createCreditNoteCounter operation.
	//
	// Creates the first credit note number which is then increased by one with every new credit note. By
	// sending an empty request body the default is base number 10000 (the first credit note number will
	// thus be 10001), but can be specified to another starting value.
	//
	// POST /companies/{companySlug}/creditNotes/counter
	CreateCreditNoteCounter(ctx context.Context, req OptCounter, params CreateCreditNoteCounterParams) error
	// CreateCreditNoteDraft implements createCreditNoteDraft operation.
	//
	// Creates a credit note draft. This draft corresponds to a draft for an "uavhengig kreditnota" in
	// Fiken.
	//
	// POST /companies/{companySlug}/creditNotes/drafts
	CreateCreditNoteDraft(ctx context.Context, req *InvoiceishDraftRequest, params CreateCreditNoteDraftParams) (*CreateCreditNoteDraftCreated, error)
	// CreateCreditNoteFromDraft implements createCreditNoteFromDraft operation.
	//
	// Creates a credit note from an already created draft.
	//
	// POST /companies/{companySlug}/creditNotes/drafts/{draftId}/createCreditNote
	CreateCreditNoteFromDraft(ctx context.Context, params CreateCreditNoteFromDraftParams) (*CreateCreditNoteFromDraftCreated, error)
	// CreateFullCreditNote implements createFullCreditNote operation.
	//
	// Creates a new credit note that covers the full amount of the associated invoice.
	//
	// POST /companies/{companySlug}/creditNotes/full
	CreateFullCreditNote(ctx context.Context, req *FullCreditNoteRequest, params CreateFullCreditNoteParams) (*CreateFullCreditNoteCreated, error)
	// CreateGeneralJournalEntry implements createGeneralJournalEntry operation.
	//
	// Creates a new general journal entry (fri postering).
	//
	// POST /companies/{companySlug}/generalJournalEntries
	CreateGeneralJournalEntry(ctx context.Context, req *GeneralJournalEntryRequest, params CreateGeneralJournalEntryParams) (*CreateGeneralJournalEntryCreated, error)
	// CreateInboxDocument implements createInboxDocument operation.
	//
	// Upload a document to the inbox.
	//
	// POST /companies/{companySlug}/inbox
	CreateInboxDocument(ctx context.Context, req *CreateInboxDocumentReq, params CreateInboxDocumentParams) (*CreateInboxDocumentCreated, error)
	// CreateInvoice implements createInvoice operation.
	//
	// Creates an invoice. This corresponds to "Ny faktura" in Fiken.
	// There are two types of invoice lines that can be added to an invoice line: product line or free
	// text line.
	// Provide a product Id if you are invoicing a product. All information regarding the price and VAT
	// for this product will be added to the invoice.
	// It is however also possible to override the unit amount by sending information in both fields
	// "productId" and "unitAmount".
	// An invoice line can also be a free text line meaning that no existing product will be associated
	// with the invoiced line.
	// In this case all information regarding the price and VAT of the product or service to be invoiced
	// must be provided.
	//
	// POST /companies/{companySlug}/invoices
	CreateInvoice(ctx context.Context, req *InvoiceRequest, params CreateInvoiceParams) (*CreateInvoiceCreated, error)
	// CreateInvoiceCounter implements createInvoiceCounter operation.
	//
	// Creates the first invoice number which is then increased by one with every new invoice. By sending
	// an empty request body the default is base number 10000 (the first invoice number will thus be
	// 10001), but can be specified to another starting value.
	//
	// POST /companies/{companySlug}/invoices/counter
	CreateInvoiceCounter(ctx context.Context, req OptCounter, params CreateInvoiceCounterParams) error
	// CreateInvoiceDraft implements createInvoiceDraft operation.
	//
	// Creates an invoice draft.
	//
	// POST /companies/{companySlug}/invoices/drafts
	CreateInvoiceDraft(ctx context.Context, req *InvoiceishDraftRequest, params CreateInvoiceDraftParams) (*CreateInvoiceDraftCreated, error)
	// CreateInvoiceDraftFromOrderConfirmation implements createInvoiceDraftFromOrderConfirmation operation.
	//
	// Creates an invoice draft from an order confirmation.
	//
	// POST /companies/{companySlug}/orderConfirmations/{confirmationId}/createInvoiceDraft
	CreateInvoiceDraftFromOrderConfirmation(ctx context.Context, params CreateInvoiceDraftFromOrderConfirmationParams) (*CreateInvoiceDraftFromOrderConfirmationCreated, error)
	// CreateInvoiceDraftFromTimeEntries implements createInvoiceDraftFromTimeEntries operation.
	//
	// Creates an invoice draft from one or more time entries.
	// The time entries will be converted to invoice lines based on the specified grouping.
	// After successful creation, the included time entries will be marked as "in draft" and
	// cannot be modified until the draft is deleted or converted to an invoice.
	// **Grouping options:**
	// - activity: One invoice line per activity, summing hours across all selected time entries for that
	// activity
	// - activityAndPerson: One invoice line per unique activity+person combination
	// - none: Each time entry becomes its own invoice line
	// **Line description:**
	// By default, the invoice line description is generated from the activity name and total hours.
	// If `includeTimeEntryDescriptions` is true, individual time entry descriptions are appended.
	//
	// POST /companies/{companySlug}/timeEntries/createInvoiceDraft
	CreateInvoiceDraftFromTimeEntries(ctx context.Context, req *TimeEntryInvoiceDraftRequest, params CreateInvoiceDraftFromTimeEntriesParams) (*InvoiceishDraftResultHeaders, error)
	// CreateInvoiceFromDraft implements createInvoiceFromDraft operation.
	//
	// Creates an invoice from an already created draft.
	//
	// POST /companies/{companySlug}/invoices/drafts/{draftId}/createInvoice
	CreateInvoiceFromDraft(ctx context.Context, params CreateInvoiceFromDraftParams) (*CreateInvoiceFromDraftCreated, error)
	// CreateOfferCounter implements createOfferCounter operation.
	//
	// Creates the first offer number which is then increased by one with every new offer. By sending an
	// empty request body the default is base number (the first offer number will thus be 10001), but can
	// be specified to another starting value.
	//
	// POST /companies/{companySlug}/offers/counter
	CreateOfferCounter(ctx context.Context, req OptCounter, params CreateOfferCounterParams) error
	// CreateOfferDraft implements createOfferDraft operation.
	//
	// Creates an offer draft.
	//
	// POST /companies/{companySlug}/offers/drafts
	CreateOfferDraft(ctx context.Context, req *InvoiceishDraftRequest, params CreateOfferDraftParams) (*CreateOfferDraftCreated, error)
	// CreateOfferFromDraft implements createOfferFromDraft operation.
	//
	// Creates an offer from an already created draft.
	//
	// POST /companies/{companySlug}/offers/drafts/{draftId}/createOffer
	CreateOfferFromDraft(ctx context.Context, params CreateOfferFromDraftParams) (*CreateOfferFromDraftCreated, error)
	// CreateOrderConfirmationCounter implements createOrderConfirmationCounter operation.
	//
	// Creates the first order confirmation number which is then increased by one with every new order
	// confirmation. By sending an empty request body the default is base number (the first order
	// confirmation number will thus be 10001), but can be specified to another starting value.
	//
	// POST /companies/{companySlug}/orderConfirmations/counter
	CreateOrderConfirmationCounter(ctx context.Context, req OptCounter, params CreateOrderConfirmationCounterParams) error
	// CreateOrderConfirmationDraft implements createOrderConfirmationDraft operation.
	//
	// Creates an order confirmation draft.
	//
	// POST /companies/{companySlug}/orderConfirmations/drafts
	CreateOrderConfirmationDraft(ctx context.Context, req *InvoiceishDraftRequest, params CreateOrderConfirmationDraftParams) (*CreateOrderConfirmationDraftCreated, error)
	// CreateOrderConfirmationFromDraft implements createOrderConfirmationFromDraft operation.
	//
	// Creates an order confirmation from an already created draft.
	//
	// POST /companies/{companySlug}/orderConfirmations/drafts/{draftId}/createOrderConfirmation
	CreateOrderConfirmationFromDraft(ctx context.Context, params CreateOrderConfirmationFromDraftParams) (*CreateOrderConfirmationFromDraftCreated, error)
	// CreatePartialCreditNote implements createPartialCreditNote operation.
	//
	// Creates a new credit note that doesn't fully cover the total amount of the associated invoice.
	//
	// POST /companies/{companySlug}/creditNotes/partial
	CreatePartialCreditNote(ctx context.Context, req *PartialCreditNoteRequest, params CreatePartialCreditNoteParams) (*CreatePartialCreditNoteCreated, error)
	// CreateProduct implements createProduct operation.
	//
	// Creates a new product.
	//
	// POST /companies/{companySlug}/products
	CreateProduct(ctx context.Context, req *Product, params CreateProductParams) (*CreateProductCreated, error)
	// CreateProductSalesReport implements createProductSalesReport operation.
	//
	// Creates a report based on provided specifications.
	//
	// POST /companies/{companySlug}/products/salesReport
	CreateProductSalesReport(ctx context.Context, req *ProductSalesReportRequest, params CreateProductSalesReportParams) ([]ProductSalesReportResult, error)
	// CreateProject implements createProject operation.
	//
	// Creates a new project.
	//
	// POST /companies/{companySlug}/projects
	CreateProject(ctx context.Context, req *ProjectRequest, params CreateProjectParams) (*CreateProjectCreated, error)
	// CreatePurchase implements createPurchase operation.
	//
	// Creates a new purchase.
	//
	// POST /companies/{companySlug}/purchases
	CreatePurchase(ctx context.Context, req *PurchaseRequest, params CreatePurchaseParams) (*CreatePurchaseCreated, error)
	// CreatePurchaseDraft implements createPurchaseDraft operation.
	//
	// Creates a purchase draft.
	//
	// POST /companies/{companySlug}/purchases/drafts
	CreatePurchaseDraft(ctx context.Context, req *DraftRequest, params CreatePurchaseDraftParams) (*CreatePurchaseDraftCreated, error)
	// CreatePurchaseFromDraft implements createPurchaseFromDraft operation.
	//
	// Creates a purchase from an already created draft.
	//
	// POST /companies/{companySlug}/purchases/drafts/{draftId}/createPurchase
	CreatePurchaseFromDraft(ctx context.Context, params CreatePurchaseFromDraftParams) (*CreatePurchaseFromDraftCreated, error)
	// CreatePurchasePayment implements createPurchasePayment operation.
	//
	// Creates a new payment for a purchase.
	//
	// POST /companies/{companySlug}/purchases/{purchaseId}/payments
	CreatePurchasePayment(ctx context.Context, req *Payment, params CreatePurchasePaymentParams) (*CreatePurchasePaymentCreated, error)
	// CreateSale implements createSale operation.
	//
	// Creates a new sale. This corresponds to "Annet salg" in Fiken and should be used when the invoice
	// document and invoice number have been created outside Fiken. Otherwise the invoices-endpoints
	// should be used.
	//
	// POST /companies/{companySlug}/sales
	CreateSale(ctx context.Context, req *SaleRequest, params CreateSaleParams) (*CreateSaleCreated, error)
	// CreateSaleDraft implements createSaleDraft operation.
	//
	// Creates a sale draft.
	//
	// POST /companies/{companySlug}/sales/drafts
	CreateSaleDraft(ctx context.Context, req *DraftRequest, params CreateSaleDraftParams) (*CreateSaleDraftCreated, error)
	// CreateSaleFromDraft implements createSaleFromDraft operation.
	//
	// Creates a sale from an already created draft.
	//
	// POST /companies/{companySlug}/sales/drafts/{draftId}/createSale
	CreateSaleFromDraft(ctx context.Context, params CreateSaleFromDraftParams) (*CreateSaleFromDraftCreated, error)
	// CreateSalePayment implements createSalePayment operation.
	//
	// Creates a new payment for a given sale.
	//
	// POST /companies/{companySlug}/sales/{saleId}/payments
	CreateSalePayment(ctx context.Context, req *Payment, params CreateSalePaymentParams) (*CreateSalePaymentCreated, error)
	// CreateTimeEntry implements createTimeEntry operation.
	//
	// Creates a new time entry.
	//
	// POST /companies/{companySlug}/timeEntries
	CreateTimeEntry(ctx context.Context, req *TimeEntryRequest, params CreateTimeEntryParams) (*CreateTimeEntryCreated, error)
	// DeleteActivity implements deleteActivity operation.
	//
	// Delete or archive activity with specified id.
	// **Behavior:**
	// - If the activity has no associated time entries and is not set as a default activity on any
	// project, it will be permanently deleted
	// - If the activity has associated time entries or is set as a default activity on a project, it
	// will be **archived** instead of deleted
	// - Archived activities are hidden from selection lists but remain accessible for historical time
	// entries
	// The response is 204 in both cases (deleted or archived).
	//
	// DELETE /companies/{companySlug}/activities/{activityId}
	DeleteActivity(ctx context.Context, params DeleteActivityParams) error
	// DeleteContact implements deleteContact operation.
	//
	// Deletes the contact if possible (no associated journal entries/sales/invoices/etc). If not
	// possible to delete will set the contact to inactive.
	//
	// DELETE /companies/{companySlug}/contacts/{contactId}
	DeleteContact(ctx context.Context, params DeleteContactParams) (DeleteContactRes, error)
	// DeleteContactContactPerson implements deleteContactContactPerson operation.
	//
	// Delete a contact's contact person.
	//
	// DELETE /companies/{companySlug}/contacts/{contactId}/contactPerson/{contactPersonId}
	DeleteContactContactPerson(ctx context.Context, params DeleteContactContactPersonParams) error
	// DeleteCreditNoteDraft implements deleteCreditNoteDraft operation.
	//
	// Delete credit note draft with specified id.
	//
	// DELETE /companies/{companySlug}/creditNotes/drafts/{draftId}
	DeleteCreditNoteDraft(ctx context.Context, params DeleteCreditNoteDraftParams) error
	// DeleteInvoiceDraft implements deleteInvoiceDraft operation.
	//
	// Delete invoice draft with specified id.
	//
	// DELETE /companies/{companySlug}/invoices/drafts/{draftId}
	DeleteInvoiceDraft(ctx context.Context, params DeleteInvoiceDraftParams) error
	// DeleteOfferDraft implements deleteOfferDraft operation.
	//
	// Delete offer draft with specified id.
	//
	// DELETE /companies/{companySlug}/offers/drafts/{draftId}
	DeleteOfferDraft(ctx context.Context, params DeleteOfferDraftParams) error
	// DeleteOrderConfirmationDraft implements deleteOrderConfirmationDraft operation.
	//
	// Delete order confirmation draft with specified id.
	//
	// DELETE /companies/{companySlug}/orderConfirmations/drafts/{draftId}
	DeleteOrderConfirmationDraft(ctx context.Context, params DeleteOrderConfirmationDraftParams) error
	// DeleteProduct implements deleteProduct operation.
	//
	// Delete product with specified id.
	//
	// DELETE /companies/{companySlug}/products/{productId}
	DeleteProduct(ctx context.Context, params DeleteProductParams) error
	// DeleteProject implements deleteProject operation.
	//
	// Delete project with specified id.
	//
	// DELETE /companies/{companySlug}/projects/{projectId}
	DeleteProject(ctx context.Context, params DeleteProjectParams) error
	// DeletePurchase implements deletePurchase operation.
	//
	// Sets the deleted flag for a purchase. The purchase is not deleted, but a reverse transaction is
	// created and the "deleted" property is set to true.
	//
	// PATCH /companies/{companySlug}/purchases/{purchaseId}/delete
	DeletePurchase(ctx context.Context, params DeletePurchaseParams) (*PurchaseResult, error)
	// DeletePurchaseDraft implements deletePurchaseDraft operation.
	//
	// Delete draft with specified id.
	//
	// DELETE /companies/{companySlug}/purchases/drafts/{draftId}
	DeletePurchaseDraft(ctx context.Context, params DeletePurchaseDraftParams) error
	// DeleteSale implements deleteSale operation.
	//
	// Sets the deleted flag for a sale. The sale is not deleted, but a reverse transaction is created
	// and the "deleted" property is set to true.
	//
	// PATCH /companies/{companySlug}/sales/{saleId}/delete
	DeleteSale(ctx context.Context, params DeleteSaleParams) (*SaleResult, error)
	// DeleteSaleDraft implements deleteSaleDraft operation.
	//
	// Delete draft with specified id.
	//
	// DELETE /companies/{companySlug}/sales/drafts/{draftId}
	DeleteSaleDraft(ctx context.Context, params DeleteSaleDraftParams) error
	// DeleteTimeEntry implements deleteTimeEntry operation.
	//
	// Delete time entry with specified id.
	// **Restrictions:**
	// - Cannot delete if the time entry has been invoiced
	// - Cannot delete if the time entry belongs to a closed accounting period
	// Returns 400 Bad Request if deletion is not allowed due to these restrictions.
	//
	// DELETE /companies/{companySlug}/timeEntries/{timeEntryId}
	DeleteTimeEntry(ctx context.Context, params DeleteTimeEntryParams) (DeleteTimeEntryRes, error)
	// DeleteTransaction implements deleteTransaction operation.
	//
	// Sets the deleted flag for a transaction. The transaction is not deleted, but a reverse transaction
	// is created and
	// the "deleted" property is set to true.
	//
	// PATCH /companies/{companySlug}/transactions/{transactionId}/delete
	DeleteTransaction(ctx context.Context, params DeleteTransactionParams) (*Transaction, error)
	// GetAccount implements getAccount operation.
	//
	// Retrieves the specified bookkeping account.
	// An account is a string with either four digits, or four digits, a colon and five digits
	// ("reskontro").
	// Examples:
	// 3020 and 1500:10001.
	//
	// GET /companies/{companySlug}/accounts/{accountCode}
	GetAccount(ctx context.Context, params GetAccountParams) (*Account, error)
	// GetAccountBalance implements getAccountBalance operation.
	//
	// Retrieves the specified bookkeping account and balance for a given date.
	//
	// GET /companies/{companySlug}/accountBalances/{accountCode}
	GetAccountBalance(ctx context.Context, params GetAccountBalanceParams) (*AccountBalance, error)
	// GetAccountBalances implements getAccountBalances operation.
	//
	// Retrieves the bookkeeping accounts and closing balances for a given date.
	// An account is a string with either four digits, or four digits, a colon and five digits
	// ("reskontro").
	// Examples:
	// 3020 and 1500:10001.
	//
	// GET /companies/{companySlug}/accountBalances
	GetAccountBalances(ctx context.Context, params GetAccountBalancesParams) (*GetAccountBalancesOKHeaders, error)
	// GetAccounts implements getAccounts operation.
	//
	// Retrieves the bookkeeping accounts for the current year.
	//
	// GET /companies/{companySlug}/accounts
	GetAccounts(ctx context.Context, params GetAccountsParams) (*GetAccountsOKHeaders, error)
	// GetActivities implements getActivities operation.
	//
	// Returns all activities for given company.
	//
	// GET /companies/{companySlug}/activities
	GetActivities(ctx context.Context, params GetActivitiesParams) (*GetActivitiesOKHeaders, error)
	// GetActivity implements getActivity operation.
	//
	// Returns activity with specified id.
	//
	// GET /companies/{companySlug}/activities/{activityId}
	GetActivity(ctx context.Context, params GetActivityParams) (*ActivityResult, error)
	// GetBankAccount implements getBankAccount operation.
	//
	// Retrieves specified bank account.
	//
	// GET /companies/{companySlug}/bankAccounts/{bankAccountId}
	GetBankAccount(ctx context.Context, params GetBankAccountParams) (*BankAccountResult, error)
	// GetBankAccounts implements getBankAccounts operation.
	//
	// Retrieves all bank accounts associated with the company.
	//
	// GET /companies/{companySlug}/bankAccounts
	GetBankAccounts(ctx context.Context, params GetBankAccountsParams) (*GetBankAccountsOKHeaders, error)
	// GetBankBalances implements getBankBalances operation.
	//
	// Retrieves all bank balances for the specified company.
	//
	// GET /companies/{companySlug}/bankBalances
	GetBankBalances(ctx context.Context, params GetBankBalancesParams) (*GetBankBalancesOKHeaders, error)
	// GetCompanies implements getCompanies operation.
	//
	// Returns all companies from the system that the user has access to. The user can update which
	// companies a given app has
	// access to in Fiken under Brukerinnstillinger -> Sikkerhet -> Apper du har gitt tilgang til.
	//
	// GET /companies
	GetCompanies(ctx context.Context, params GetCompaniesParams) (*GetCompaniesOKHeaders, error)
	// GetCompany implements getCompany operation.
	//
	// Returns company associated with slug.
	//
	// GET /companies/{companySlug}
	GetCompany(ctx context.Context, params GetCompanyParams) (*Company, error)
	// GetContact implements getContact operation.
	//
	// Retrieves specified contact. ContactId is returned with a GET contacts call as the first returned
	// field.
	// ContactId is returned in the Location response header for POST contact.
	//
	// GET /companies/{companySlug}/contacts/{contactId}
	GetContact(ctx context.Context, params GetContactParams) (*Contact, error)
	// GetContactContactPerson implements getContactContactPerson operation.
	//
	// Retrieves contact person(s) for a specified contact.
	//
	// GET /companies/{companySlug}/contacts/{contactId}/contactPerson
	GetContactContactPerson(ctx context.Context, params GetContactContactPersonParams) ([]ContactPerson, error)
	// GetContactPerson implements getContactPerson operation.
	//
	// Retrieves specified contact person.
	//
	// GET /companies/{companySlug}/contacts/{contactId}/contactPerson/{contactPersonId}
	GetContactPerson(ctx context.Context, params GetContactPersonParams) (*ContactPerson, error)
	// GetContacts implements getContacts operation.
	//
	// Retrieves all contacts for the specified company.
	//
	// GET /companies/{companySlug}/contacts
	GetContacts(ctx context.Context, params GetContactsParams) (*GetContactsOKHeaders, error)
	// GetCreditNote implements getCreditNote operation.
	//
	// Returns credit note with specified id.
	//
	// GET /companies/{companySlug}/creditNotes/{creditNoteId}
	GetCreditNote(ctx context.Context, params GetCreditNoteParams) (*CreditNoteResult, error)
	// GetCreditNoteCounter implements getCreditNoteCounter operation.
	//
	// Retrieves the counter for credit notes if it has been created.
	//
	// GET /companies/{companySlug}/creditNotes/counter
	GetCreditNoteCounter(ctx context.Context, params GetCreditNoteCounterParams) (*Counter, error)
	// GetCreditNoteDraft implements getCreditNoteDraft operation.
	//
	// Returns credit note draft with specified id.
	//
	// GET /companies/{companySlug}/creditNotes/drafts/{draftId}
	GetCreditNoteDraft(ctx context.Context, params GetCreditNoteDraftParams) (*InvoiceishDraftResult, error)
	// GetCreditNoteDraftAttachments implements getCreditNoteDraftAttachments operation.
	//
	// Returns all attachments for specified draft.
	//
	// GET /companies/{companySlug}/creditNotes/drafts/{draftId}/attachments
	GetCreditNoteDraftAttachments(ctx context.Context, params GetCreditNoteDraftAttachmentsParams) ([]Attachment, error)
	// GetCreditNoteDrafts implements getCreditNoteDrafts operation.
	//
	// Returns all credit note drafts for given company.
	//
	// GET /companies/{companySlug}/creditNotes/drafts
	GetCreditNoteDrafts(ctx context.Context, params GetCreditNoteDraftsParams) (*GetCreditNoteDraftsOKHeaders, error)
	// GetCreditNotes implements getCreditNotes operation.
	//
	// Returns all credit notes for given company.
	//
	// GET /companies/{companySlug}/creditNotes
	GetCreditNotes(ctx context.Context, params GetCreditNotesParams) (*GetCreditNotesOKHeaders, error)
	// GetGroups implements getGroups operation.
	//
	// Returns all customer groups for given company.
	//
	// GET /companies/{companySlug}/groups
	GetGroups(ctx context.Context, params GetGroupsParams) (*GetGroupsOKHeaders, error)
	// GetInbox implements getInbox operation.
	//
	// Returns the contents of the inbox for given company.
	//
	// GET /companies/{companySlug}/inbox
	GetInbox(ctx context.Context, params GetInboxParams) (*GetInboxOKHeaders, error)
	// GetInboxDocument implements getInboxDocument operation.
	//
	// Returns the inbox document with specified id.
	//
	// GET /companies/{companySlug}/inbox/{inboxDocumentId}
	GetInboxDocument(ctx context.Context, params GetInboxDocumentParams) (*InboxResult, error)
	// GetInvoice implements getInvoice operation.
	//
	// Returns invoice with specified id.
	//
	// GET /companies/{companySlug}/invoices/{invoiceId}
	GetInvoice(ctx context.Context, params GetInvoiceParams) (*InvoiceResult, error)
	// GetInvoiceAttachments implements getInvoiceAttachments operation.
	//
	// Returns all attachments for a given Invoice.
	//
	// GET /companies/{companySlug}/invoices/{invoiceId}/attachments
	GetInvoiceAttachments(ctx context.Context, params GetInvoiceAttachmentsParams) ([]Attachment, error)
	// GetInvoiceCounter implements getInvoiceCounter operation.
	//
	// Retrieves the counter for invoices if it has been created.
	//
	// GET /companies/{companySlug}/invoices/counter
	GetInvoiceCounter(ctx context.Context, params GetInvoiceCounterParams) (*Counter, error)
	// GetInvoiceDraft implements getInvoiceDraft operation.
	//
	// Returns invoice draft with specified id.
	//
	// GET /companies/{companySlug}/invoices/drafts/{draftId}
	GetInvoiceDraft(ctx context.Context, params GetInvoiceDraftParams) (*InvoiceishDraftResult, error)
	// GetInvoiceDraftAttachments implements getInvoiceDraftAttachments operation.
	//
	// Returns all attachments for specified draft.
	//
	// GET /companies/{companySlug}/invoices/drafts/{draftId}/attachments
	GetInvoiceDraftAttachments(ctx context.Context, params GetInvoiceDraftAttachmentsParams) ([]Attachment, error)
	// GetInvoiceDrafts implements getInvoiceDrafts operation.
	//
	// Returns all invoice drafts for given company.
	//
	// GET /companies/{companySlug}/invoices/drafts
	GetInvoiceDrafts(ctx context.Context, params GetInvoiceDraftsParams) (*GetInvoiceDraftsOKHeaders, error)
	// GetInvoices implements getInvoices operation.
	//
	// Returns all invoices for given company. You can filter based on issue date, last modified date,
	// customer ID, and if the invoice is settled or not.
	//
	// GET /companies/{companySlug}/invoices
	GetInvoices(ctx context.Context, params GetInvoicesParams) (*GetInvoicesOKHeaders, error)
	// GetJournalEntries implements getJournalEntries operation.
	//
	// Returns all general journal entries (posteringer) for the specified company.
	//
	// GET /companies/{companySlug}/journalEntries
	GetJournalEntries(ctx context.Context, params GetJournalEntriesParams) (*GetJournalEntriesOKHeaders, error)
	// GetJournalEntry implements getJournalEntry operation.
	//
	// Returns all journal entries within a given company's Journal Entry Service.
	//
	// GET /companies/{companySlug}/journalEntries/{journalEntryId}
	GetJournalEntry(ctx context.Context, params GetJournalEntryParams) (*JournalEntry, error)
	// GetJournalEntryAttachments implements getJournalEntryAttachments operation.
	//
	// Returns all attachments for a given Journal Entry.
	//
	// GET /companies/{companySlug}/journalEntries/{journalEntryId}/attachments
	GetJournalEntryAttachments(ctx context.Context, params GetJournalEntryAttachmentsParams) ([]Attachment, error)
	// GetOffer implements getOffer operation.
	//
	// Returns offer with specified id.
	//
	// GET /companies/{companySlug}/offers/{offerId}
	GetOffer(ctx context.Context, params GetOfferParams) (*Offer, error)
	// GetOfferCounter implements getOfferCounter operation.
	//
	// Retrieves the counter for offers if it has been created.
	//
	// GET /companies/{companySlug}/offers/counter
	GetOfferCounter(ctx context.Context, params GetOfferCounterParams) (*Counter, error)
	// GetOfferDraft implements getOfferDraft operation.
	//
	// Returns offer draft with specified id.
	//
	// GET /companies/{companySlug}/offers/drafts/{draftId}
	GetOfferDraft(ctx context.Context, params GetOfferDraftParams) (*InvoiceishDraftResult, error)
	// GetOfferDraftAttachments implements getOfferDraftAttachments operation.
	//
	// Returns all attachments for specified draft.
	//
	// GET /companies/{companySlug}/offers/drafts/{draftId}/attachments
	GetOfferDraftAttachments(ctx context.Context, params GetOfferDraftAttachmentsParams) ([]Attachment, error)
	// GetOfferDrafts implements getOfferDrafts operation.
	//
	// Returns all offer drafts for given company.
	//
	// GET /companies/{companySlug}/offers/drafts
	GetOfferDrafts(ctx context.Context, params GetOfferDraftsParams) (*GetOfferDraftsOKHeaders, error)
	// GetOffers implements getOffers operation.
	//
	// Returns all offers for given company.
	//
	// GET /companies/{companySlug}/offers
	GetOffers(ctx context.Context, params GetOffersParams) (*GetOffersOKHeaders, error)
	// GetOrderConfirmation implements getOrderConfirmation operation.
	//
	// Returns order confirmation with specified id.
	//
	// GET /companies/{companySlug}/orderConfirmations/{confirmationId}
	GetOrderConfirmation(ctx context.Context, params GetOrderConfirmationParams) (*OrderConfirmation, error)
	// GetOrderConfirmationCounter implements getOrderConfirmationCounter operation.
	//
	// Retrieves the counter for order confirmations if it has been created.
	//
	// GET /companies/{companySlug}/orderConfirmations/counter
	GetOrderConfirmationCounter(ctx context.Context, params GetOrderConfirmationCounterParams) (*Counter, error)
	// GetOrderConfirmationDraft implements getOrderConfirmationDraft operation.
	//
	// Returns order confirmation draft with specified id.
	//
	// GET /companies/{companySlug}/orderConfirmations/drafts/{draftId}
	GetOrderConfirmationDraft(ctx context.Context, params GetOrderConfirmationDraftParams) (*InvoiceishDraftResult, error)
	// GetOrderConfirmationDraftAttachments implements getOrderConfirmationDraftAttachments operation.
	//
	// Returns all attachments for specified draft.
	//
	// GET /companies/{companySlug}/orderConfirmations/drafts/{draftId}/attachments
	GetOrderConfirmationDraftAttachments(ctx context.Context, params GetOrderConfirmationDraftAttachmentsParams) ([]Attachment, error)
	// GetOrderConfirmationDrafts implements getOrderConfirmationDrafts operation.
	//
	// Returns all order confirmation drafts for given company.
	//
	// GET /companies/{companySlug}/orderConfirmations/drafts
	GetOrderConfirmationDrafts(ctx context.Context, params GetOrderConfirmationDraftsParams) (*GetOrderConfirmationDraftsOKHeaders, error)
	// GetOrderConfirmations implements getOrderConfirmations operation.
	//
	// Returns all order confirmations for given company.
	//
	// GET /companies/{companySlug}/orderConfirmations
	GetOrderConfirmations(ctx context.Context, params GetOrderConfirmationsParams) (*GetOrderConfirmationsOKHeaders, error)
	// GetProduct implements getProduct operation.
	//
	// Returns product with specified id.
	//
	// GET /companies/{companySlug}/products/{productId}
	GetProduct(ctx context.Context, params GetProductParams) (*Product, error)
	// GetProducts implements getProducts operation.
	//
	// Returns all products for given company.
	//
	// GET /companies/{companySlug}/products
	GetProducts(ctx context.Context, params GetProductsParams) (*GetProductsOKHeaders, error)
	// GetProject implements getProject operation.
	//
	// Returns project with specified id.
	//
	// GET /companies/{companySlug}/projects/{projectId}
	GetProject(ctx context.Context, params GetProjectParams) (*ProjectResult, error)
	// GetProjects implements getProjects operation.
	//
	// Returns all projects for given company.
	//
	// GET /companies/{companySlug}/projects
	GetProjects(ctx context.Context, params GetProjectsParams) (*GetProjectsOKHeaders, error)
	// GetPurchase implements getPurchase operation.
	//
	// Returns purchase with specified id.
	//
	// GET /companies/{companySlug}/purchases/{purchaseId}
	GetPurchase(ctx context.Context, params GetPurchaseParams) (*PurchaseResult, error)
	// GetPurchaseAttachments implements getPurchaseAttachments operation.
	//
	// Returns all attachments for specified purchase.
	//
	// GET /companies/{companySlug}/purchases/{purchaseId}/attachments
	GetPurchaseAttachments(ctx context.Context, params GetPurchaseAttachmentsParams) ([]Attachment, error)
	// GetPurchaseDraft implements getPurchaseDraft operation.
	//
	// Returns draft with specified id.
	//
	// GET /companies/{companySlug}/purchases/drafts/{draftId}
	GetPurchaseDraft(ctx context.Context, params GetPurchaseDraftParams) (*DraftResult, error)
	// GetPurchaseDraftAttachments implements getPurchaseDraftAttachments operation.
	//
	// Returns all attachments for specified draft.
	//
	// GET /companies/{companySlug}/purchases/drafts/{draftId}/attachments
	GetPurchaseDraftAttachments(ctx context.Context, params GetPurchaseDraftAttachmentsParams) ([]Attachment, error)
	// GetPurchaseDrafts implements getPurchaseDrafts operation.
	//
	// Returns all purchase drafts for given company.
	//
	// GET /companies/{companySlug}/purchases/drafts
	GetPurchaseDrafts(ctx context.Context, params GetPurchaseDraftsParams) (*GetPurchaseDraftsOKHeaders, error)
	// GetPurchasePayment implements getPurchasePayment operation.
	//
	// Returns given payment for specified purchase.
	//
	// GET /companies/{companySlug}/purchases/{purchaseId}/payments/{paymentId}
	GetPurchasePayment(ctx context.Context, params GetPurchasePaymentParams) (*Payment, error)
	// GetPurchasePayments implements getPurchasePayments operation.
	//
	// Returns all purchases for given company.
	//
	// GET /companies/{companySlug}/purchases/{purchaseId}/payments
	GetPurchasePayments(ctx context.Context, params GetPurchasePaymentsParams) ([]Payment, error)
	// GetPurchases implements getPurchases operation.
	//
	// Returns all purchases for given company.
	//
	// GET /companies/{companySlug}/purchases
	GetPurchases(ctx context.Context, params GetPurchasesParams) (*GetPurchasesOKHeaders, error)
	// GetSale implements getSale operation.
	//
	// Returns sale with specified id.
	//
	// GET /companies/{companySlug}/sales/{saleId}
	GetSale(ctx context.Context, params GetSaleParams) (*SaleResult, error)
	// GetSaleAttachments implements getSaleAttachments operation.
	//
	// Returns all attachments for specified sale.
	//
	// GET /companies/{companySlug}/sales/{saleId}/attachments
	GetSaleAttachments(ctx context.Context, params GetSaleAttachmentsParams) ([]Attachment, error)
	// GetSaleDraft implements getSaleDraft operation.
	//
	// Returns draft with specified id.
	//
	// GET /companies/{companySlug}/sales/drafts/{draftId}
	GetSaleDraft(ctx context.Context, params GetSaleDraftParams) (*DraftResult, error)
	// GetSaleDraftAttachments implements getSaleDraftAttachments operation.
	//
	// Returns all attachments for specified draft.
	//
	// GET /companies/{companySlug}/sales/drafts/{draftId}/attachments
	GetSaleDraftAttachments(ctx context.Context, params GetSaleDraftAttachmentsParams) ([]Attachment, error)
	// GetSaleDrafts implements getSaleDrafts operation.
	//
	// Returns all sale drafts for given company.
	//
	// GET /companies/{companySlug}/sales/drafts
	GetSaleDrafts(ctx context.Context, params GetSaleDraftsParams) (*GetSaleDraftsOKHeaders, error)
	// GetSalePayment implements getSalePayment operation.
	//
	// Returns payment with specified id.
	//
	// GET /companies/{companySlug}/sales/{saleId}/payments/{paymentId}
	GetSalePayment(ctx context.Context, params GetSalePaymentParams) (*Payment, error)
	// GetSalePayments implements getSalePayments operation.
	//
	// Returns all payments for given sale.
	//
	// GET /companies/{companySlug}/sales/{saleId}/payments
	GetSalePayments(ctx context.Context, params GetSalePaymentsParams) ([]Payment, error)
	// GetSales implements getSales operation.
	//
	// Returns all sales for given company.
	//
	// GET /companies/{companySlug}/sales
	GetSales(ctx context.Context, params GetSalesParams) (*GetSalesOKHeaders, error)
	// GetTimeEntries implements getTimeEntries operation.
	//
	// Returns all time entries for given company.
	//
	// GET /companies/{companySlug}/timeEntries
	GetTimeEntries(ctx context.Context, params GetTimeEntriesParams) (*GetTimeEntriesOKHeaders, error)
	// GetTimeEntry implements getTimeEntry operation.
	//
	// Returns time entry with specified id.
	//
	// GET /companies/{companySlug}/timeEntries/{timeEntryId}
	GetTimeEntry(ctx context.Context, params GetTimeEntryParams) (*TimeEntryResult, error)
	// GetTimeUser implements getTimeUser operation.
	//
	// Returns time user with specified id.
	//
	// GET /companies/{companySlug}/timeUsers/{timeUserId}
	GetTimeUser(ctx context.Context, params GetTimeUserParams) (*TimeUserResult, error)
	// GetTimeUsers implements getTimeUsers operation.
	//
	// Returns all persons who can register time entries for the given company.
	//
	// GET /companies/{companySlug}/timeUsers
	GetTimeUsers(ctx context.Context, params GetTimeUsersParams) (*GetTimeUsersOKHeaders, error)
	// GetTransaction implements getTransaction operation.
	//
	// Returns given transaction with associated id. Transaction id is returned in GET calls for
	// sales, purchases, and journal entries.
	//
	// GET /companies/{companySlug}/transactions/{transactionId}
	GetTransaction(ctx context.Context, params GetTransactionParams) (*Transaction, error)
	// GetTransactions implements getTransactions operation.
	//
	// Returns all transactions for the specified company.
	//
	// GET /companies/{companySlug}/transactions
	GetTransactions(ctx context.Context, params GetTransactionsParams) (*GetTransactionsOKHeaders, error)
	// GetUser implements getUser operation.
	//
	// Returns information about the user.
	//
	// GET /user
	GetUser(ctx context.Context) (*Userinfo, error)
	// SendCreditNote implements sendCreditNote operation.
	//
	// Sends the specified document.
	//
	// POST /companies/{companySlug}/creditNotes/send
	SendCreditNote(ctx context.Context, req *SendCreditNoteRequest, params SendCreditNoteParams) error
	// SendInvoice implements sendInvoice operation.
	//
	// Sends the specified document.
	//
	// POST /companies/{companySlug}/invoices/send
	SendInvoice(ctx context.Context, req *SendInvoiceRequest, params SendInvoiceParams) error
	// SendOffer implements sendOffer operation.
	//
	// Sends the specified document.
	//
	// POST /companies/{companySlug}/offers/send
	SendOffer(ctx context.Context, req *SendOfferRequest, params SendOfferParams) error
	// SettledSale implements settledSale operation.
	//
	// Marks the sale as settled without payment. This is synonymous with "sett til oppgjort uten
	// betaling" in the GUI. It is possible to change the date of settlement by sending a new settledDate.
	//
	// PATCH /companies/{companySlug}/sales/{saleId}/settled
	SettledSale(ctx context.Context, params SettledSaleParams) (*SaleResult, error)
	// UpdateActivity implements updateActivity operation.
	//
	// Partially updates activity with provided id. Only provided fields will be updated.
	//
	// PATCH /companies/{companySlug}/activities/{activityId}
	UpdateActivity(ctx context.Context, req *UpdateActivityRequest, params UpdateActivityParams) (*UpdateActivityOK, error)
	// UpdateContact implements updateContact operation.
	//
	// Updates an existing contact.
	//
	// PUT /companies/{companySlug}/contacts/{contactId}
	UpdateContact(ctx context.Context, req *Contact, params UpdateContactParams) (*UpdateContactOK, error)
	// UpdateContactContactPerson implements updateContactContactPerson operation.
	//
	// Updates an existing contact person.
	//
	// PUT /companies/{companySlug}/contacts/{contactId}/contactPerson/{contactPersonId}
	UpdateContactContactPerson(ctx context.Context, req *ContactPerson, params UpdateContactContactPersonParams) (*UpdateContactContactPersonOK, error)
	// UpdateCreditNoteDraft implements updateCreditNoteDraft operation.
	//
	// Updates credit note draft with provided id.
	//
	// PUT /companies/{companySlug}/creditNotes/drafts/{draftId}
	UpdateCreditNoteDraft(ctx context.Context, req *InvoiceishDraftRequest, params UpdateCreditNoteDraftParams) (*UpdateCreditNoteDraftCreated, error)
	// UpdateInvoice implements updateInvoice operation.
	//
	// Updates invoice with provided id. It is possible to update the due date of an invoice
	// as well as if the invoice was sent manually, outside of Fiken.
	//
	// PATCH /companies/{companySlug}/invoices/{invoiceId}
	UpdateInvoice(ctx context.Context, req *UpdateInvoiceRequest, params UpdateInvoiceParams) (*UpdateInvoiceOK, error)
	// UpdateInvoiceDraft implements updateInvoiceDraft operation.
	//
	// Updates invoice draft with provided id.
	//
	// PUT /companies/{companySlug}/invoices/drafts/{draftId}
	UpdateInvoiceDraft(ctx context.Context, req *InvoiceishDraftRequest, params UpdateInvoiceDraftParams) (*UpdateInvoiceDraftCreated, error)
	// UpdateOfferDraft implements updateOfferDraft operation.
	//
	// Updates offer draft with provided id.
	//
	// PUT /companies/{companySlug}/offers/drafts/{draftId}
	UpdateOfferDraft(ctx context.Context, req *InvoiceishDraftRequest, params UpdateOfferDraftParams) (*UpdateOfferDraftCreated, error)
	// UpdateOrderConfirmationDraft implements updateOrderConfirmationDraft operation.
	//
	// Updates order confirmation draft with provided id.
	//
	// PUT /companies/{companySlug}/orderConfirmations/drafts/{draftId}
	UpdateOrderConfirmationDraft(ctx context.Context, req *InvoiceishDraftRequest, params UpdateOrderConfirmationDraftParams) (*UpdateOrderConfirmationDraftCreated, error)
	// UpdateProduct implements updateProduct operation.
	//
	// Updates an existing product.
	//
	// PUT /companies/{companySlug}/products/{productId}
	UpdateProduct(ctx context.Context, req *Product, params UpdateProductParams) (*UpdateProductOK, error)
	// UpdateProject implements updateProject operation.
	//
	// Updates project with provided id.
	//
	// PATCH /companies/{companySlug}/projects/{projectId}
	UpdateProject(ctx context.Context, req *UpdateProjectRequest, params UpdateProjectParams) (*UpdateProjectCreated, error)
	// UpdatePurchaseDraft implements updatePurchaseDraft operation.
	//
	// Updates draft with provided id.
	//
	// PUT /companies/{companySlug}/purchases/drafts/{draftId}
	UpdatePurchaseDraft(ctx context.Context, req *DraftRequest, params UpdatePurchaseDraftParams) (*UpdatePurchaseDraftCreated, error)
	// UpdateSaleDraft implements updateSaleDraft operation.
	//
	// Updates draft with provided id.
	//
	// PUT /companies/{companySlug}/sales/drafts/{draftId}
	UpdateSaleDraft(ctx context.Context, req *DraftRequest, params UpdateSaleDraftParams) (*UpdateSaleDraftCreated, error)
	// UpdateTimeEntry implements updateTimeEntry operation.
	//
	// Partially updates time entry with provided id. Only provided fields will be updated.
	//
	// PATCH /companies/{companySlug}/timeEntries/{timeEntryId}
	UpdateTimeEntry(ctx context.Context, req *UpdateTimeEntryRequest, params UpdateTimeEntryParams) (*UpdateTimeEntryOK, error)
	// WriteOffSale implements writeOffSale operation.
	//
	// Registers a write-off (tapsføring) for the given sale. The sale must not be a cash sale, must not
	// already be written off, settled, or deleted, and must have an outstanding balance. The write-off
	// date must be after the sale date.
	//
	// PATCH /companies/{companySlug}/sales/{saleId}/writeOff
	WriteOffSale(ctx context.Context, req *WriteOffRequest, params WriteOffSaleParams) (*SaleResult, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
