// Code generated by ogen, DO NOT EDIT.

package fiken

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleFikenAPIOAuth handles fiken_api_oauth security.
	HandleFikenAPIOAuth(ctx context.Context, operationName OperationName, t FikenAPIOAuth) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// oauth2ScopesFikenAPIOAuth is a private map storing OAuth2 scopes per operation.
var oauth2ScopesFikenAPIOAuth = map[string][]string{
	AddAttachmentToContactOperation:                  {},
	AddAttachmentToCreditNoteDraftOperation:          {},
	AddAttachmentToInvoiceOperation:                  {},
	AddAttachmentToInvoiceDraftOperation:             {},
	AddAttachmentToJournalEntryOperation:             {},
	AddAttachmentToOfferDraftOperation:               {},
	AddAttachmentToOrderConfirmationDraftOperation:   {},
	AddAttachmentToPurchaseOperation:                 {},
	AddAttachmentToPurchaseDraftOperation:            {},
	AddAttachmentToSaleOperation:                     {},
	AddAttachmentToSaleDraftOperation:                {},
	AddContactPersonToContactOperation:               {},
	CreateActivityOperation:                          {},
	CreateBankAccountOperation:                       {},
	CreateContactOperation:                           {},
	CreateCreditNoteCounterOperation:                 {},
	CreateCreditNoteDraftOperation:                   {},
	CreateCreditNoteFromDraftOperation:               {},
	CreateFullCreditNoteOperation:                    {},
	CreateGeneralJournalEntryOperation:               {},
	CreateInboxDocumentOperation:                     {},
	CreateInvoiceOperation:                           {},
	CreateInvoiceCounterOperation:                    {},
	CreateInvoiceDraftOperation:                      {},
	CreateInvoiceDraftFromOrderConfirmationOperation: {},
	CreateInvoiceDraftFromTimeEntriesOperation:       {},
	CreateInvoiceFromDraftOperation:                  {},
	CreateOfferCounterOperation:                      {},
	CreateOfferDraftOperation:                        {},
	CreateOfferFromDraftOperation:                    {},
	CreateOrderConfirmationCounterOperation:          {},
	CreateOrderConfirmationDraftOperation:            {},
	CreateOrderConfirmationFromDraftOperation:        {},
	CreatePartialCreditNoteOperation:                 {},
	CreateProductOperation:                           {},
	CreateProductSalesReportOperation:                {},
	CreateProjectOperation:                           {},
	CreatePurchaseOperation:                          {},
	CreatePurchaseDraftOperation:                     {},
	CreatePurchaseFromDraftOperation:                 {},
	CreatePurchasePaymentOperation:                   {},
	CreateSaleOperation:                              {},
	CreateSaleDraftOperation:                         {},
	CreateSaleFromDraftOperation:                     {},
	CreateSalePaymentOperation:                       {},
	CreateTimeEntryOperation:                         {},
	DeleteActivityOperation:                          {},
	DeleteContactOperation:                           {},
	DeleteContactContactPersonOperation:              {},
	DeleteCreditNoteDraftOperation:                   {},
	DeleteInvoiceDraftOperation:                      {},
	DeleteOfferDraftOperation:                        {},
	DeleteOrderConfirmationDraftOperation:            {},
	DeleteProductOperation:                           {},
	DeleteProjectOperation:                           {},
	DeletePurchaseOperation:                          {},
	DeletePurchaseDraftOperation:                     {},
	DeleteSaleOperation:                              {},
	DeleteSaleDraftOperation:                         {},
	DeleteTimeEntryOperation:                         {},
	DeleteTransactionOperation:                       {},
	GetAccountOperation:                              {},
	GetAccountBalanceOperation:                       {},
	GetAccountBalancesOperation:                      {},
	GetAccountsOperation:                             {},
	GetActivitiesOperation:                           {},
	GetActivityOperation:                             {},
	GetBankAccountOperation:                          {},
	GetBankAccountsOperation:                         {},
	GetBankBalancesOperation:                         {},
	GetCompaniesOperation:                            {},
	GetCompanyOperation:                              {},
	GetContactOperation:                              {},
	GetContactContactPersonOperation:                 {},
	GetContactPersonOperation:                        {},
	GetContactsOperation:                             {},
	GetCreditNoteOperation:                           {},
	GetCreditNoteCounterOperation:                    {},
	GetCreditNoteDraftOperation:                      {},
	GetCreditNoteDraftAttachmentsOperation:           {},
	GetCreditNoteDraftsOperation:                     {},
	GetCreditNotesOperation:                          {},
	GetGroupsOperation:                               {},
	GetInboxOperation:                                {},
	GetInboxDocumentOperation:                        {},
	GetInvoiceOperation:                              {},
	GetInvoiceAttachmentsOperation:                   {},
	GetInvoiceCounterOperation:                       {},
	GetInvoiceDraftOperation:                         {},
	GetInvoiceDraftAttachmentsOperation:              {},
	GetInvoiceDraftsOperation:                        {},
	GetInvoicesOperation:                             {},
	GetJournalEntriesOperation:                       {},
	GetJournalEntryOperation:                         {},
	GetJournalEntryAttachmentsOperation:              {},
	GetOfferOperation:                                {},
	GetOfferCounterOperation:                         {},
	GetOfferDraftOperation:                           {},
	GetOfferDraftAttachmentsOperation:                {},
	GetOfferDraftsOperation:                          {},
	GetOffersOperation:                               {},
	GetOrderConfirmationOperation:                    {},
	GetOrderConfirmationCounterOperation:             {},
	GetOrderConfirmationDraftOperation:               {},
	GetOrderConfirmationDraftAttachmentsOperation:    {},
	GetOrderConfirmationDraftsOperation:              {},
	GetOrderConfirmationsOperation:                   {},
	GetProductOperation:                              {},
	GetProductsOperation:                             {},
	GetProjectOperation:                              {},
	GetProjectsOperation:                             {},
	GetPurchaseOperation:                             {},
	GetPurchaseAttachmentsOperation:                  {},
	GetPurchaseDraftOperation:                        {},
	GetPurchaseDraftAttachmentsOperation:             {},
	GetPurchaseDraftsOperation:                       {},
	GetPurchasePaymentOperation:                      {},
	GetPurchasePaymentsOperation:                     {},
	GetPurchasesOperation:                            {},
	GetSaleOperation:                                 {},
	GetSaleAttachmentsOperation:                      {},
	GetSaleDraftOperation:                            {},
	GetSaleDraftAttachmentsOperation:                 {},
	GetSaleDraftsOperation:                           {},
	GetSalePaymentOperation:                          {},
	GetSalePaymentsOperation:                         {},
	GetSalesOperation:                                {},
	GetTimeEntriesOperation:                          {},
	GetTimeEntryOperation:                            {},
	GetTimeUserOperation:                             {},
	GetTimeUsersOperation:                            {},
	GetTransactionOperation:                          {},
	GetTransactionsOperation:                         {},
	GetUserOperation:                                 {},
	SendCreditNoteOperation:                          {},
	SendInvoiceOperation:                             {},
	SendOfferOperation:                               {},
	SettledSaleOperation:                             {},
	UpdateActivityOperation:                          {},
	UpdateContactOperation:                           {},
	UpdateContactContactPersonOperation:              {},
	UpdateCreditNoteDraftOperation:                   {},
	UpdateInvoiceOperation:                           {},
	UpdateInvoiceDraftOperation:                      {},
	UpdateOfferDraftOperation:                        {},
	UpdateOrderConfirmationDraftOperation:            {},
	UpdateProductOperation:                           {},
	UpdateProjectOperation:                           {},
	UpdatePurchaseDraftOperation:                     {},
	UpdateSaleDraftOperation:                         {},
	UpdateTimeEntryOperation:                         {},
	WriteOffSaleOperation:                            {},
}

// GetOAuth2ScopesForFikenAPIOAuth returns the required OAuth2 scopes for the given operation.
//
// This is useful for token exchange scenarios where you need to know which scopes
// to request when obtaining a token for a downstream API call.
//
// Example:
//
//	requiredScopes := GetOAuth2ScopesForFikenAPIOAuth(AddPetOperation)
//	token := exchangeTokenWithScopes(requiredScopes, "https://api.example.com")
//
// Returns nil if the operation has no scope requirements or if the operation is unknown.
func GetOAuth2ScopesForFikenAPIOAuth(operation string) []string {
	scopes, ok := oauth2ScopesFikenAPIOAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(scopes))
	copy(result, scopes)
	return result
}

func (s *Server) securityFikenAPIOAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t FikenAPIOAuth
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Scopes = oauth2ScopesFikenAPIOAuth[operationName]
	rctx, err := s.sec.HandleFikenAPIOAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// FikenAPIOAuth provides fiken_api_oauth security value.
	FikenAPIOAuth(ctx context.Context, operationName OperationName) (FikenAPIOAuth, error)
}

func (s *Client) securityFikenAPIOAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.FikenAPIOAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"FikenAPIOAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
