// Code generated by ogen, DO NOT EDIT.

package fiken

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddAttachmentToContact implements addAttachmentToContact operation.
//
// Creates and adds a new attachment/document to a contact.
//
// POST /companies/{companySlug}/contacts/{contactId}/attachments
func (UnimplementedHandler) AddAttachmentToContact(ctx context.Context, req OptAddAttachmentToContactReq, params AddAttachmentToContactParams) (r *AddAttachmentToContactCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// AddAttachmentToCreditNoteDraft implements addAttachmentToCreditNoteDraft operation.
//
// Creates and adds a new attachment to a credit note draft.
//
// POST /companies/{companySlug}/creditNotes/drafts/{draftId}/attachments
func (UnimplementedHandler) AddAttachmentToCreditNoteDraft(ctx context.Context, req OptAddAttachmentToCreditNoteDraftReq, params AddAttachmentToCreditNoteDraftParams) (r *AddAttachmentToCreditNoteDraftCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// AddAttachmentToInvoice implements addAttachmentToInvoice operation.
//
// Creates and adds a new attachment to an Invoice.
//
// POST /companies/{companySlug}/invoices/{invoiceId}/attachments
func (UnimplementedHandler) AddAttachmentToInvoice(ctx context.Context, req OptAddAttachmentToInvoiceReq, params AddAttachmentToInvoiceParams) (r *AddAttachmentToInvoiceCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// AddAttachmentToInvoiceDraft implements addAttachmentToInvoiceDraft operation.
//
// Creates and adds a new attachment to an invoice draft.
//
// POST /companies/{companySlug}/invoices/drafts/{draftId}/attachments
func (UnimplementedHandler) AddAttachmentToInvoiceDraft(ctx context.Context, req OptAddAttachmentToInvoiceDraftReq, params AddAttachmentToInvoiceDraftParams) (r *AddAttachmentToInvoiceDraftCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// AddAttachmentToJournalEntry implements addAttachmentToJournalEntry operation.
//
// Creates and adds a new attachment to a Journal Entry.
//
// POST /companies/{companySlug}/journalEntries/{journalEntryId}/attachments
func (UnimplementedHandler) AddAttachmentToJournalEntry(ctx context.Context, req OptAddAttachmentToJournalEntryReq, params AddAttachmentToJournalEntryParams) (r *AddAttachmentToJournalEntryCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// AddAttachmentToOfferDraft implements addAttachmentToOfferDraft operation.
//
// Creates and adds a new attachment to an offer draft.
//
// POST /companies/{companySlug}/offers/drafts/{draftId}/attachments
func (UnimplementedHandler) AddAttachmentToOfferDraft(ctx context.Context, req OptAddAttachmentToOfferDraftReq, params AddAttachmentToOfferDraftParams) (r *AddAttachmentToOfferDraftCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// AddAttachmentToOrderConfirmationDraft implements addAttachmentToOrderConfirmationDraft operation.
//
// Creates and adds a new attachment to an order confirmation draft.
//
// POST /companies/{companySlug}/orderConfirmations/drafts/{draftId}/attachments
func (UnimplementedHandler) AddAttachmentToOrderConfirmationDraft(ctx context.Context, req OptAddAttachmentToOrderConfirmationDraftReq, params AddAttachmentToOrderConfirmationDraftParams) (r *AddAttachmentToOrderConfirmationDraftCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// AddAttachmentToPurchase implements addAttachmentToPurchase operation.
//
// Creates and adds a new attachment to a Purchase.
//
// POST /companies/{companySlug}/purchases/{purchaseId}/attachments
func (UnimplementedHandler) AddAttachmentToPurchase(ctx context.Context, req OptAddAttachmentToPurchaseReq, params AddAttachmentToPurchaseParams) (r *AddAttachmentToPurchaseCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// AddAttachmentToPurchaseDraft implements addAttachmentToPurchaseDraft operation.
//
// Creates and adds a new attachment to a draft.
//
// POST /companies/{companySlug}/purchases/drafts/{draftId}/attachments
func (UnimplementedHandler) AddAttachmentToPurchaseDraft(ctx context.Context, req OptAddAttachmentToPurchaseDraftReq, params AddAttachmentToPurchaseDraftParams) (r *AddAttachmentToPurchaseDraftCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// AddAttachmentToSale implements addAttachmentToSale operation.
//
// Creates and adds a new attachment to a Sale.
//
// POST /companies/{companySlug}/sales/{saleId}/attachments
func (UnimplementedHandler) AddAttachmentToSale(ctx context.Context, req OptAddAttachmentToSaleReq, params AddAttachmentToSaleParams) (r *AddAttachmentToSaleCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// AddAttachmentToSaleDraft implements addAttachmentToSaleDraft operation.
//
// Creates and adds a new attachment to a draft.
//
// POST /companies/{companySlug}/sales/drafts/{draftId}/attachments
func (UnimplementedHandler) AddAttachmentToSaleDraft(ctx context.Context, req OptAddAttachmentToSaleDraftReq, params AddAttachmentToSaleDraftParams) (r *AddAttachmentToSaleDraftCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// AddContactPersonToContact implements addContactPersonToContact operation.
//
// Adds a new contact person to a contact.
//
// POST /companies/{companySlug}/contacts/{contactId}/contactPerson
func (UnimplementedHandler) AddContactPersonToContact(ctx context.Context, req *ContactPerson, params AddContactPersonToContactParams) (r *AddContactPersonToContactOK, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateActivity implements createActivity operation.
//
// Creates a new activity.
//
// POST /companies/{companySlug}/activities
func (UnimplementedHandler) CreateActivity(ctx context.Context, req *ActivityRequest, params CreateActivityParams) (r *CreateActivityCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateBankAccount implements createBankAccount operation.
//
// Creates a new bank account. The Location response header returns the URL of the newly created bank
// account. Possible types of bank accounts are NORMAL, TAX_DEDUCTION, FOREIGN, and CREDIT_CARD. The
// field "foreignService" should only be filled out for accounts of type FOREIGN.
//
// POST /companies/{companySlug}/bankAccounts
func (UnimplementedHandler) CreateBankAccount(ctx context.Context, req *BankAccountRequest, params CreateBankAccountParams) (r *CreateBankAccountCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateContact implements createContact operation.
//
// Creates a new contact. The Location response header returns the URL of the newly created contact.
//
// POST /companies/{companySlug}/contacts
func (UnimplementedHandler) CreateContact(ctx context.Context, req *Contact, params CreateContactParams) (r *CreateContactCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateCreditNoteCounter implements createCreditNoteCounter operation.
//
// Creates the first credit note number which is then increased by one with every new credit note. By
// sending an empty request body the default is base number 10000 (the first credit note number will
// thus be 10001), but can be specified to another starting value.
//
// POST /companies/{companySlug}/creditNotes/counter
func (UnimplementedHandler) CreateCreditNoteCounter(ctx context.Context, req OptCounter, params CreateCreditNoteCounterParams) error {
	return ht.ErrNotImplemented
}

// CreateCreditNoteDraft implements createCreditNoteDraft operation.
//
// Creates a credit note draft. This draft corresponds to a draft for an "uavhengig kreditnota" in
// Fiken.
//
// POST /companies/{companySlug}/creditNotes/drafts
func (UnimplementedHandler) CreateCreditNoteDraft(ctx context.Context, req *InvoiceishDraftRequest, params CreateCreditNoteDraftParams) (r *CreateCreditNoteDraftCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateCreditNoteFromDraft implements createCreditNoteFromDraft operation.
//
// Creates a credit note from an already created draft.
//
// POST /companies/{companySlug}/creditNotes/drafts/{draftId}/createCreditNote
func (UnimplementedHandler) CreateCreditNoteFromDraft(ctx context.Context, params CreateCreditNoteFromDraftParams) (r *CreateCreditNoteFromDraftCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateFullCreditNote implements createFullCreditNote operation.
//
// Creates a new credit note that covers the full amount of the associated invoice.
//
// POST /companies/{companySlug}/creditNotes/full
func (UnimplementedHandler) CreateFullCreditNote(ctx context.Context, req *FullCreditNoteRequest, params CreateFullCreditNoteParams) (r *CreateFullCreditNoteCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateGeneralJournalEntry implements createGeneralJournalEntry operation.
//
// Creates a new general journal entry (fri postering).
//
// POST /companies/{companySlug}/generalJournalEntries
func (UnimplementedHandler) CreateGeneralJournalEntry(ctx context.Context, req *GeneralJournalEntryRequest, params CreateGeneralJournalEntryParams) (r *CreateGeneralJournalEntryCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateInboxDocument implements createInboxDocument operation.
//
// Upload a document to the inbox.
//
// POST /companies/{companySlug}/inbox
func (UnimplementedHandler) CreateInboxDocument(ctx context.Context, req *CreateInboxDocumentReq, params CreateInboxDocumentParams) (r *CreateInboxDocumentCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateInvoice implements createInvoice operation.
//
// Creates an invoice. This corresponds to "Ny faktura" in Fiken. There are two types of invoice lines
// that can be added to an invoice line: product line or free text line. Provide a product Id if you
// are invoicing a product. All information regarding the price and VAT for this product will be added
// to the invoice. It is however also possible to override the unit amount by sending information in
// both fields "productId" and "unitAmount". An invoice line can also be a free text line meaning that
// no existing product will be associated with the invoiced line. In this case all information
// regarding the price and VAT of the product or service to be invoiced must be provided.
//
// POST /companies/{companySlug}/invoices
func (UnimplementedHandler) CreateInvoice(ctx context.Context, req *InvoiceRequest, params CreateInvoiceParams) (r *CreateInvoiceCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateInvoiceCounter implements createInvoiceCounter operation.
//
// Creates the first invoice number which is then increased by one with every new invoice. By sending
// an empty request body the default is base number 10000 (the first invoice number will thus be
// 10001), but can be specified to another starting value.
//
// POST /companies/{companySlug}/invoices/counter
func (UnimplementedHandler) CreateInvoiceCounter(ctx context.Context, req OptCounter, params CreateInvoiceCounterParams) error {
	return ht.ErrNotImplemented
}

// CreateInvoiceDraft implements createInvoiceDraft operation.
//
// Creates an invoice draft.
//
// POST /companies/{companySlug}/invoices/drafts
func (UnimplementedHandler) CreateInvoiceDraft(ctx context.Context, req *InvoiceishDraftRequest, params CreateInvoiceDraftParams) (r *CreateInvoiceDraftCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateInvoiceDraftFromOrderConfirmation implements createInvoiceDraftFromOrderConfirmation operation.
//
// Creates an invoice draft from an order confirmation.
//
// POST /companies/{companySlug}/orderConfirmations/{confirmationId}/createInvoiceDraft
func (UnimplementedHandler) CreateInvoiceDraftFromOrderConfirmation(ctx context.Context, params CreateInvoiceDraftFromOrderConfirmationParams) (r *CreateInvoiceDraftFromOrderConfirmationCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateInvoiceDraftFromTimeEntries implements createInvoiceDraftFromTimeEntries operation.
//
// Creates an invoice draft from one or more time entries.
//
// The time entries will be converted to invoice lines based on the specified grouping. After
// successful creation, the included time entries will be marked as "in draft" and cannot be modified
// until the draft is deleted or converted to an invoice.
//
// Grouping options:
//
//   - activity: One invoice line per activity, summing hours across all selected time entries for that
//     activity
//   - activityAndPerson: One invoice line per unique activity+person combination
//   - none: Each time entry becomes its own invoice line
//
// Line description: By default, the invoice line description is generated from the activity name and
// total hours. If `includeTimeEntryDescriptions` is true, individual time entry descriptions are
// appended.
//
// POST /companies/{companySlug}/timeEntries/createInvoiceDraft
func (UnimplementedHandler) CreateInvoiceDraftFromTimeEntries(ctx context.Context, req *TimeEntryInvoiceDraftRequest, params CreateInvoiceDraftFromTimeEntriesParams) (r *InvoiceishDraftResultHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateInvoiceFromDraft implements createInvoiceFromDraft operation.
//
// Creates an invoice from an already created draft.
//
// POST /companies/{companySlug}/invoices/drafts/{draftId}/createInvoice
func (UnimplementedHandler) CreateInvoiceFromDraft(ctx context.Context, params CreateInvoiceFromDraftParams) (r *CreateInvoiceFromDraftCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOfferCounter implements createOfferCounter operation.
//
// Creates the first offer number which is then increased by one with every new offer. By sending an
// empty request body the default is base number (the first offer number will thus be 10001), but can
// be specified to another starting value.
//
// POST /companies/{companySlug}/offers/counter
func (UnimplementedHandler) CreateOfferCounter(ctx context.Context, req OptCounter, params CreateOfferCounterParams) error {
	return ht.ErrNotImplemented
}

// CreateOfferDraft implements createOfferDraft operation.
//
// Creates an offer draft.
//
// POST /companies/{companySlug}/offers/drafts
func (UnimplementedHandler) CreateOfferDraft(ctx context.Context, req *InvoiceishDraftRequest, params CreateOfferDraftParams) (r *CreateOfferDraftCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOfferFromDraft implements createOfferFromDraft operation.
//
// Creates an offer from an already created draft.
//
// POST /companies/{companySlug}/offers/drafts/{draftId}/createOffer
func (UnimplementedHandler) CreateOfferFromDraft(ctx context.Context, params CreateOfferFromDraftParams) (r *CreateOfferFromDraftCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrderConfirmationCounter implements createOrderConfirmationCounter operation.
//
// Creates the first order confirmation number which is then increased by one with every new order
// confirmation. By sending an empty request body the default is base number (the first order
// confirmation number will thus be 10001), but can be specified to another starting value.
//
// POST /companies/{companySlug}/orderConfirmations/counter
func (UnimplementedHandler) CreateOrderConfirmationCounter(ctx context.Context, req OptCounter, params CreateOrderConfirmationCounterParams) error {
	return ht.ErrNotImplemented
}

// CreateOrderConfirmationDraft implements createOrderConfirmationDraft operation.
//
// Creates an order confirmation draft.
//
// POST /companies/{companySlug}/orderConfirmations/drafts
func (UnimplementedHandler) CreateOrderConfirmationDraft(ctx context.Context, req *InvoiceishDraftRequest, params CreateOrderConfirmationDraftParams) (r *CreateOrderConfirmationDraftCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrderConfirmationFromDraft implements createOrderConfirmationFromDraft operation.
//
// Creates an order confirmation from an already created draft.
//
// POST /companies/{companySlug}/orderConfirmations/drafts/{draftId}/createOrderConfirmation
func (UnimplementedHandler) CreateOrderConfirmationFromDraft(ctx context.Context, params CreateOrderConfirmationFromDraftParams) (r *CreateOrderConfirmationFromDraftCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePartialCreditNote implements createPartialCreditNote operation.
//
// Creates a new credit note that doesn't fully cover the total amount of the associated invoice.
//
// POST /companies/{companySlug}/creditNotes/partial
func (UnimplementedHandler) CreatePartialCreditNote(ctx context.Context, req *PartialCreditNoteRequest, params CreatePartialCreditNoteParams) (r *CreatePartialCreditNoteCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateProduct implements createProduct operation.
//
// Creates a new product.
//
// POST /companies/{companySlug}/products
func (UnimplementedHandler) CreateProduct(ctx context.Context, req *Product, params CreateProductParams) (r *CreateProductCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateProductSalesReport implements createProductSalesReport operation.
//
// Creates a report based on provided specifications.
//
// POST /companies/{companySlug}/products/salesReport
func (UnimplementedHandler) CreateProductSalesReport(ctx context.Context, req *ProductSalesReportRequest, params CreateProductSalesReportParams) (r []ProductSalesReportResult, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateProject implements createProject operation.
//
// Creates a new project.
//
// POST /companies/{companySlug}/projects
func (UnimplementedHandler) CreateProject(ctx context.Context, req *ProjectRequest, params CreateProjectParams) (r *CreateProjectCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePurchase implements createPurchase operation.
//
// Creates a new purchase.
//
// POST /companies/{companySlug}/purchases
func (UnimplementedHandler) CreatePurchase(ctx context.Context, req *PurchaseRequest, params CreatePurchaseParams) (r *CreatePurchaseCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePurchaseDraft implements createPurchaseDraft operation.
//
// Creates a purchase draft.
//
// POST /companies/{companySlug}/purchases/drafts
func (UnimplementedHandler) CreatePurchaseDraft(ctx context.Context, req *DraftRequest, params CreatePurchaseDraftParams) (r *CreatePurchaseDraftCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePurchaseFromDraft implements createPurchaseFromDraft operation.
//
// Creates a purchase from an already created draft.
//
// POST /companies/{companySlug}/purchases/drafts/{draftId}/createPurchase
func (UnimplementedHandler) CreatePurchaseFromDraft(ctx context.Context, params CreatePurchaseFromDraftParams) (r *CreatePurchaseFromDraftCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePurchasePayment implements createPurchasePayment operation.
//
// Creates a new payment for a purchase.
//
// POST /companies/{companySlug}/purchases/{purchaseId}/payments
func (UnimplementedHandler) CreatePurchasePayment(ctx context.Context, req *Payment, params CreatePurchasePaymentParams) (r *CreatePurchasePaymentCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSale implements createSale operation.
//
// Creates a new sale. This corresponds to "Annet salg" in Fiken and should be used when the invoice
// document and invoice number have been created outside Fiken. Otherwise the invoices-endpoints should
// be used.
//
// POST /companies/{companySlug}/sales
func (UnimplementedHandler) CreateSale(ctx context.Context, req *SaleRequest, params CreateSaleParams) (r *CreateSaleCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSaleDraft implements createSaleDraft operation.
//
// Creates a sale draft.
//
// POST /companies/{companySlug}/sales/drafts
func (UnimplementedHandler) CreateSaleDraft(ctx context.Context, req *DraftRequest, params CreateSaleDraftParams) (r *CreateSaleDraftCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSaleFromDraft implements createSaleFromDraft operation.
//
// Creates a sale from an already created draft.
//
// POST /companies/{companySlug}/sales/drafts/{draftId}/createSale
func (UnimplementedHandler) CreateSaleFromDraft(ctx context.Context, params CreateSaleFromDraftParams) (r *CreateSaleFromDraftCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSalePayment implements createSalePayment operation.
//
// Creates a new payment for a given sale.
//
// POST /companies/{companySlug}/sales/{saleId}/payments
func (UnimplementedHandler) CreateSalePayment(ctx context.Context, req *Payment, params CreateSalePaymentParams) (r *CreateSalePaymentCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTimeEntry implements createTimeEntry operation.
//
// Creates a new time entry.
//
// POST /companies/{companySlug}/timeEntries
func (UnimplementedHandler) CreateTimeEntry(ctx context.Context, req *TimeEntryRequest, params CreateTimeEntryParams) (r *CreateTimeEntryCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteActivity implements deleteActivity operation.
//
// Delete or archive activity with specified id.
//
// Behavior:
//
//   - If the activity has no associated time entries and is not set as a default activity on any
//     project, it will be permanently deleted
//   - If the activity has associated time entries or is set as a default activity on a project, it will
//     be archived instead of deleted
//   - Archived activities are hidden from selection lists but remain accessible for historical time
//     entries
//
// The response is 204 in both cases (deleted or archived).
//
// DELETE /companies/{companySlug}/activities/{activityId}
func (UnimplementedHandler) DeleteActivity(ctx context.Context, params DeleteActivityParams) error {
	return ht.ErrNotImplemented
}

// DeleteContact implements deleteContact operation.
//
// Deletes the contact if possible (no associated journal entries/sales/invoices/etc). If not possible
// to delete will set the contact to inactive.
//
// DELETE /companies/{companySlug}/contacts/{contactId}
func (UnimplementedHandler) DeleteContact(ctx context.Context, params DeleteContactParams) (r DeleteContactRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteContactContactPerson implements deleteContactContactPerson operation.
//
// Delete a contact's contact person.
//
// DELETE /companies/{companySlug}/contacts/{contactId}/contactPerson/{contactPersonId}
func (UnimplementedHandler) DeleteContactContactPerson(ctx context.Context, params DeleteContactContactPersonParams) error {
	return ht.ErrNotImplemented
}

// DeleteCreditNoteDraft implements deleteCreditNoteDraft operation.
//
// Delete credit note draft with specified id.
//
// DELETE /companies/{companySlug}/creditNotes/drafts/{draftId}
func (UnimplementedHandler) DeleteCreditNoteDraft(ctx context.Context, params DeleteCreditNoteDraftParams) error {
	return ht.ErrNotImplemented
}

// DeleteInvoiceDraft implements deleteInvoiceDraft operation.
//
// Delete invoice draft with specified id.
//
// DELETE /companies/{companySlug}/invoices/drafts/{draftId}
func (UnimplementedHandler) DeleteInvoiceDraft(ctx context.Context, params DeleteInvoiceDraftParams) error {
	return ht.ErrNotImplemented
}

// DeleteOfferDraft implements deleteOfferDraft operation.
//
// Delete offer draft with specified id.
//
// DELETE /companies/{companySlug}/offers/drafts/{draftId}
func (UnimplementedHandler) DeleteOfferDraft(ctx context.Context, params DeleteOfferDraftParams) error {
	return ht.ErrNotImplemented
}

// DeleteOrderConfirmationDraft implements deleteOrderConfirmationDraft operation.
//
// Delete order confirmation draft with specified id.
//
// DELETE /companies/{companySlug}/orderConfirmations/drafts/{draftId}
func (UnimplementedHandler) DeleteOrderConfirmationDraft(ctx context.Context, params DeleteOrderConfirmationDraftParams) error {
	return ht.ErrNotImplemented
}

// DeleteProduct implements deleteProduct operation.
//
// Delete product with specified id.
//
// DELETE /companies/{companySlug}/products/{productId}
func (UnimplementedHandler) DeleteProduct(ctx context.Context, params DeleteProductParams) error {
	return ht.ErrNotImplemented
}

// DeleteProject implements deleteProject operation.
//
// Delete project with specified id.
//
// DELETE /companies/{companySlug}/projects/{projectId}
func (UnimplementedHandler) DeleteProject(ctx context.Context, params DeleteProjectParams) error {
	return ht.ErrNotImplemented
}

// DeletePurchase implements deletePurchase operation.
//
// Sets the deleted flag for a purchase. The purchase is not deleted, but a reverse transaction is
// created and the "deleted" property is set to true.
//
// PATCH /companies/{companySlug}/purchases/{purchaseId}/delete
func (UnimplementedHandler) DeletePurchase(ctx context.Context, params DeletePurchaseParams) (r *PurchaseResult, _ error) {
	return r, ht.ErrNotImplemented
}

// DeletePurchaseDraft implements deletePurchaseDraft operation.
//
// Delete draft with specified id.
//
// DELETE /companies/{companySlug}/purchases/drafts/{draftId}
func (UnimplementedHandler) DeletePurchaseDraft(ctx context.Context, params DeletePurchaseDraftParams) error {
	return ht.ErrNotImplemented
}

// DeleteSale implements deleteSale operation.
//
// Sets the deleted flag for a sale. The sale is not deleted, but a reverse transaction is created and
// the "deleted" property is set to true.
//
// PATCH /companies/{companySlug}/sales/{saleId}/delete
func (UnimplementedHandler) DeleteSale(ctx context.Context, params DeleteSaleParams) (r *SaleResult, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteSaleDraft implements deleteSaleDraft operation.
//
// Delete draft with specified id.
//
// DELETE /companies/{companySlug}/sales/drafts/{draftId}
func (UnimplementedHandler) DeleteSaleDraft(ctx context.Context, params DeleteSaleDraftParams) error {
	return ht.ErrNotImplemented
}

// DeleteTimeEntry implements deleteTimeEntry operation.
//
// Delete time entry with specified id.
//
// Restrictions:
//
//   - Cannot delete if the time entry has been invoiced
//   - Cannot delete if the time entry belongs to a closed accounting period
//
// Returns 400 Bad Request if deletion is not allowed due to these restrictions.
//
// DELETE /companies/{companySlug}/timeEntries/{timeEntryId}
func (UnimplementedHandler) DeleteTimeEntry(ctx context.Context, params DeleteTimeEntryParams) (r DeleteTimeEntryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteTransaction implements deleteTransaction operation.
//
// Sets the deleted flag for a transaction. The transaction is not deleted, but a reverse transaction
// is created and the "deleted" property is set to true.
//
// PATCH /companies/{companySlug}/transactions/{transactionId}/delete
func (UnimplementedHandler) DeleteTransaction(ctx context.Context, params DeleteTransactionParams) (r *Transaction, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAccount implements getAccount operation.
//
// Retrieves the specified bookkeping account. An account is a string with either four digits, or four
// digits, a colon and five digits ("reskontro"). Examples: 3020 and 1500:10001.
//
// GET /companies/{companySlug}/accounts/{accountCode}
func (UnimplementedHandler) GetAccount(ctx context.Context, params GetAccountParams) (r *Account, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAccountBalance implements getAccountBalance operation.
//
// Retrieves the specified bookkeping account and balance for a given date.
//
// GET /companies/{companySlug}/accountBalances/{accountCode}
func (UnimplementedHandler) GetAccountBalance(ctx context.Context, params GetAccountBalanceParams) (r *AccountBalance, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAccountBalances implements getAccountBalances operation.
//
// Retrieves the bookkeeping accounts and closing balances for a given date. An account is a string
// with either four digits, or four digits, a colon and five digits ("reskontro"). Examples: 3020 and
// 1500:10001.
//
// GET /companies/{companySlug}/accountBalances
func (UnimplementedHandler) GetAccountBalances(ctx context.Context, params GetAccountBalancesParams) (r *GetAccountBalancesOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAccounts implements getAccounts operation.
//
// Retrieves the bookkeeping accounts for the current year.
//
// GET /companies/{companySlug}/accounts
func (UnimplementedHandler) GetAccounts(ctx context.Context, params GetAccountsParams) (r *GetAccountsOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetActivities implements getActivities operation.
//
// Returns all activities for given company.
//
// GET /companies/{companySlug}/activities
func (UnimplementedHandler) GetActivities(ctx context.Context, params GetActivitiesParams) (r *GetActivitiesOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetActivity implements getActivity operation.
//
// Returns activity with specified id.
//
// GET /companies/{companySlug}/activities/{activityId}
func (UnimplementedHandler) GetActivity(ctx context.Context, params GetActivityParams) (r *ActivityResult, _ error) {
	return r, ht.ErrNotImplemented
}

// GetBankAccount implements getBankAccount operation.
//
// Retrieves specified bank account.
//
// GET /companies/{companySlug}/bankAccounts/{bankAccountId}
func (UnimplementedHandler) GetBankAccount(ctx context.Context, params GetBankAccountParams) (r *BankAccountResult, _ error) {
	return r, ht.ErrNotImplemented
}

// GetBankAccounts implements getBankAccounts operation.
//
// Retrieves all bank accounts associated with the company.
//
// GET /companies/{companySlug}/bankAccounts
func (UnimplementedHandler) GetBankAccounts(ctx context.Context, params GetBankAccountsParams) (r *GetBankAccountsOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetBankBalances implements getBankBalances operation.
//
// Retrieves all bank balances for the specified company.
//
// GET /companies/{companySlug}/bankBalances
func (UnimplementedHandler) GetBankBalances(ctx context.Context, params GetBankBalancesParams) (r *GetBankBalancesOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCompanies implements getCompanies operation.
//
// Returns all companies from the system that the user has access to. The user can update which
// companies a given app has access to in Fiken under Brukerinnstillinger -> Sikkerhet -> Apper du har
// gitt tilgang til.
//
// GET /companies
func (UnimplementedHandler) GetCompanies(ctx context.Context, params GetCompaniesParams) (r *GetCompaniesOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCompany implements getCompany operation.
//
// Returns company associated with slug.
//
// GET /companies/{companySlug}
func (UnimplementedHandler) GetCompany(ctx context.Context, params GetCompanyParams) (r *Company, _ error) {
	return r, ht.ErrNotImplemented
}

// GetContact implements getContact operation.
//
// Retrieves specified contact. ContactId is returned with a GET contacts call as the first returned
// field. ContactId is returned in the Location response header for POST contact.
//
// GET /companies/{companySlug}/contacts/{contactId}
func (UnimplementedHandler) GetContact(ctx context.Context, params GetContactParams) (r *Contact, _ error) {
	return r, ht.ErrNotImplemented
}

// GetContactContactPerson implements getContactContactPerson operation.
//
// Retrieves contact person(s) for a specified contact.
//
// GET /companies/{companySlug}/contacts/{contactId}/contactPerson
func (UnimplementedHandler) GetContactContactPerson(ctx context.Context, params GetContactContactPersonParams) (r []ContactPerson, _ error) {
	return r, ht.ErrNotImplemented
}

// GetContactPerson implements getContactPerson operation.
//
// Retrieves specified contact person.
//
// GET /companies/{companySlug}/contacts/{contactId}/contactPerson/{contactPersonId}
func (UnimplementedHandler) GetContactPerson(ctx context.Context, params GetContactPersonParams) (r *ContactPerson, _ error) {
	return r, ht.ErrNotImplemented
}

// GetContacts implements getContacts operation.
//
// Retrieves all contacts for the specified company.
//
// GET /companies/{companySlug}/contacts
func (UnimplementedHandler) GetContacts(ctx context.Context, params GetContactsParams) (r *GetContactsOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCreditNote implements getCreditNote operation.
//
// Returns credit note with specified id.
//
// GET /companies/{companySlug}/creditNotes/{creditNoteId}
func (UnimplementedHandler) GetCreditNote(ctx context.Context, params GetCreditNoteParams) (r *CreditNoteResult, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCreditNoteCounter implements getCreditNoteCounter operation.
//
// Retrieves the counter for credit notes if it has been created.
//
// GET /companies/{companySlug}/creditNotes/counter
func (UnimplementedHandler) GetCreditNoteCounter(ctx context.Context, params GetCreditNoteCounterParams) (r *Counter, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCreditNoteDraft implements getCreditNoteDraft operation.
//
// Returns credit note draft with specified id.
//
// GET /companies/{companySlug}/creditNotes/drafts/{draftId}
func (UnimplementedHandler) GetCreditNoteDraft(ctx context.Context, params GetCreditNoteDraftParams) (r *InvoiceishDraftResult, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCreditNoteDraftAttachments implements getCreditNoteDraftAttachments operation.
//
// Returns all attachments for specified draft.
//
// GET /companies/{companySlug}/creditNotes/drafts/{draftId}/attachments
func (UnimplementedHandler) GetCreditNoteDraftAttachments(ctx context.Context, params GetCreditNoteDraftAttachmentsParams) (r []Attachment, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCreditNoteDrafts implements getCreditNoteDrafts operation.
//
// Returns all credit note drafts for given company.
//
// GET /companies/{companySlug}/creditNotes/drafts
func (UnimplementedHandler) GetCreditNoteDrafts(ctx context.Context, params GetCreditNoteDraftsParams) (r *GetCreditNoteDraftsOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCreditNotes implements getCreditNotes operation.
//
// Returns all credit notes for given company.
//
// GET /companies/{companySlug}/creditNotes
func (UnimplementedHandler) GetCreditNotes(ctx context.Context, params GetCreditNotesParams) (r *GetCreditNotesOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetGroups implements getGroups operation.
//
// Returns all customer groups for given company.
//
// GET /companies/{companySlug}/groups
func (UnimplementedHandler) GetGroups(ctx context.Context, params GetGroupsParams) (r *GetGroupsOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetInbox implements getInbox operation.
//
// Returns the contents of the inbox for given company.
//
// GET /companies/{companySlug}/inbox
func (UnimplementedHandler) GetInbox(ctx context.Context, params GetInboxParams) (r *GetInboxOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetInboxDocument implements getInboxDocument operation.
//
// Returns the inbox document with specified id.
//
// GET /companies/{companySlug}/inbox/{inboxDocumentId}
func (UnimplementedHandler) GetInboxDocument(ctx context.Context, params GetInboxDocumentParams) (r *InboxResult, _ error) {
	return r, ht.ErrNotImplemented
}

// GetInvoice implements getInvoice operation.
//
// Returns invoice with specified id.
//
// GET /companies/{companySlug}/invoices/{invoiceId}
func (UnimplementedHandler) GetInvoice(ctx context.Context, params GetInvoiceParams) (r *InvoiceResult, _ error) {
	return r, ht.ErrNotImplemented
}

// GetInvoiceAttachments implements getInvoiceAttachments operation.
//
// Returns all attachments for a given Invoice.
//
// GET /companies/{companySlug}/invoices/{invoiceId}/attachments
func (UnimplementedHandler) GetInvoiceAttachments(ctx context.Context, params GetInvoiceAttachmentsParams) (r []Attachment, _ error) {
	return r, ht.ErrNotImplemented
}

// GetInvoiceCounter implements getInvoiceCounter operation.
//
// Retrieves the counter for invoices if it has been created.
//
// GET /companies/{companySlug}/invoices/counter
func (UnimplementedHandler) GetInvoiceCounter(ctx context.Context, params GetInvoiceCounterParams) (r *Counter, _ error) {
	return r, ht.ErrNotImplemented
}

// GetInvoiceDraft implements getInvoiceDraft operation.
//
// Returns invoice draft with specified id.
//
// GET /companies/{companySlug}/invoices/drafts/{draftId}
func (UnimplementedHandler) GetInvoiceDraft(ctx context.Context, params GetInvoiceDraftParams) (r *InvoiceishDraftResult, _ error) {
	return r, ht.ErrNotImplemented
}

// GetInvoiceDraftAttachments implements getInvoiceDraftAttachments operation.
//
// Returns all attachments for specified draft.
//
// GET /companies/{companySlug}/invoices/drafts/{draftId}/attachments
func (UnimplementedHandler) GetInvoiceDraftAttachments(ctx context.Context, params GetInvoiceDraftAttachmentsParams) (r []Attachment, _ error) {
	return r, ht.ErrNotImplemented
}

// GetInvoiceDrafts implements getInvoiceDrafts operation.
//
// Returns all invoice drafts for given company.
//
// GET /companies/{companySlug}/invoices/drafts
func (UnimplementedHandler) GetInvoiceDrafts(ctx context.Context, params GetInvoiceDraftsParams) (r *GetInvoiceDraftsOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetInvoices implements getInvoices operation.
//
// Returns all invoices for given company. You can filter based on issue date, last modified date,
// customer ID, and if the invoice is settled or not.
//
// GET /companies/{companySlug}/invoices
func (UnimplementedHandler) GetInvoices(ctx context.Context, params GetInvoicesParams) (r *GetInvoicesOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetJournalEntries implements getJournalEntries operation.
//
// Returns all general journal entries (posteringer) for the specified company.
//
// GET /companies/{companySlug}/journalEntries
func (UnimplementedHandler) GetJournalEntries(ctx context.Context, params GetJournalEntriesParams) (r *GetJournalEntriesOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetJournalEntry implements getJournalEntry operation.
//
// Returns all journal entries within a given company's Journal Entry Service.
//
// GET /companies/{companySlug}/journalEntries/{journalEntryId}
func (UnimplementedHandler) GetJournalEntry(ctx context.Context, params GetJournalEntryParams) (r *JournalEntry, _ error) {
	return r, ht.ErrNotImplemented
}

// GetJournalEntryAttachments implements getJournalEntryAttachments operation.
//
// Returns all attachments for a given Journal Entry.
//
// GET /companies/{companySlug}/journalEntries/{journalEntryId}/attachments
func (UnimplementedHandler) GetJournalEntryAttachments(ctx context.Context, params GetJournalEntryAttachmentsParams) (r []Attachment, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOffer implements getOffer operation.
//
// Returns offer with specified id.
//
// GET /companies/{companySlug}/offers/{offerId}
func (UnimplementedHandler) GetOffer(ctx context.Context, params GetOfferParams) (r *Offer, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOfferCounter implements getOfferCounter operation.
//
// Retrieves the counter for offers if it has been created.
//
// GET /companies/{companySlug}/offers/counter
func (UnimplementedHandler) GetOfferCounter(ctx context.Context, params GetOfferCounterParams) (r *Counter, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOfferDraft implements getOfferDraft operation.
//
// Returns offer draft with specified id.
//
// GET /companies/{companySlug}/offers/drafts/{draftId}
func (UnimplementedHandler) GetOfferDraft(ctx context.Context, params GetOfferDraftParams) (r *InvoiceishDraftResult, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOfferDraftAttachments implements getOfferDraftAttachments operation.
//
// Returns all attachments for specified draft.
//
// GET /companies/{companySlug}/offers/drafts/{draftId}/attachments
func (UnimplementedHandler) GetOfferDraftAttachments(ctx context.Context, params GetOfferDraftAttachmentsParams) (r []Attachment, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOfferDrafts implements getOfferDrafts operation.
//
// Returns all offer drafts for given company.
//
// GET /companies/{companySlug}/offers/drafts
func (UnimplementedHandler) GetOfferDrafts(ctx context.Context, params GetOfferDraftsParams) (r *GetOfferDraftsOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOffers implements getOffers operation.
//
// Returns all offers for given company.
//
// GET /companies/{companySlug}/offers
func (UnimplementedHandler) GetOffers(ctx context.Context, params GetOffersParams) (r *GetOffersOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrderConfirmation implements getOrderConfirmation operation.
//
// Returns order confirmation with specified id.
//
// GET /companies/{companySlug}/orderConfirmations/{confirmationId}
func (UnimplementedHandler) GetOrderConfirmation(ctx context.Context, params GetOrderConfirmationParams) (r *OrderConfirmation, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrderConfirmationCounter implements getOrderConfirmationCounter operation.
//
// Retrieves the counter for order confirmations if it has been created.
//
// GET /companies/{companySlug}/orderConfirmations/counter
func (UnimplementedHandler) GetOrderConfirmationCounter(ctx context.Context, params GetOrderConfirmationCounterParams) (r *Counter, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrderConfirmationDraft implements getOrderConfirmationDraft operation.
//
// Returns order confirmation draft with specified id.
//
// GET /companies/{companySlug}/orderConfirmations/drafts/{draftId}
func (UnimplementedHandler) GetOrderConfirmationDraft(ctx context.Context, params GetOrderConfirmationDraftParams) (r *InvoiceishDraftResult, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrderConfirmationDraftAttachments implements getOrderConfirmationDraftAttachments operation.
//
// Returns all attachments for specified draft.
//
// GET /companies/{companySlug}/orderConfirmations/drafts/{draftId}/attachments
func (UnimplementedHandler) GetOrderConfirmationDraftAttachments(ctx context.Context, params GetOrderConfirmationDraftAttachmentsParams) (r []Attachment, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrderConfirmationDrafts implements getOrderConfirmationDrafts operation.
//
// Returns all order confirmation drafts for given company.
//
// GET /companies/{companySlug}/orderConfirmations/drafts
func (UnimplementedHandler) GetOrderConfirmationDrafts(ctx context.Context, params GetOrderConfirmationDraftsParams) (r *GetOrderConfirmationDraftsOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrderConfirmations implements getOrderConfirmations operation.
//
// Returns all order confirmations for given company.
//
// GET /companies/{companySlug}/orderConfirmations
func (UnimplementedHandler) GetOrderConfirmations(ctx context.Context, params GetOrderConfirmationsParams) (r *GetOrderConfirmationsOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProduct implements getProduct operation.
//
// Returns product with specified id.
//
// GET /companies/{companySlug}/products/{productId}
func (UnimplementedHandler) GetProduct(ctx context.Context, params GetProductParams) (r *Product, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProducts implements getProducts operation.
//
// Returns all products for given company.
//
// GET /companies/{companySlug}/products
func (UnimplementedHandler) GetProducts(ctx context.Context, params GetProductsParams) (r *GetProductsOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProject implements getProject operation.
//
// Returns project with specified id.
//
// GET /companies/{companySlug}/projects/{projectId}
func (UnimplementedHandler) GetProject(ctx context.Context, params GetProjectParams) (r *ProjectResult, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProjects implements getProjects operation.
//
// Returns all projects for given company.
//
// GET /companies/{companySlug}/projects
func (UnimplementedHandler) GetProjects(ctx context.Context, params GetProjectsParams) (r *GetProjectsOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPurchase implements getPurchase operation.
//
// Returns purchase with specified id.
//
// GET /companies/{companySlug}/purchases/{purchaseId}
func (UnimplementedHandler) GetPurchase(ctx context.Context, params GetPurchaseParams) (r *PurchaseResult, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPurchaseAttachments implements getPurchaseAttachments operation.
//
// Returns all attachments for specified purchase.
//
// GET /companies/{companySlug}/purchases/{purchaseId}/attachments
func (UnimplementedHandler) GetPurchaseAttachments(ctx context.Context, params GetPurchaseAttachmentsParams) (r []Attachment, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPurchaseDraft implements getPurchaseDraft operation.
//
// Returns draft with specified id.
//
// GET /companies/{companySlug}/purchases/drafts/{draftId}
func (UnimplementedHandler) GetPurchaseDraft(ctx context.Context, params GetPurchaseDraftParams) (r *DraftResult, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPurchaseDraftAttachments implements getPurchaseDraftAttachments operation.
//
// Returns all attachments for specified draft.
//
// GET /companies/{companySlug}/purchases/drafts/{draftId}/attachments
func (UnimplementedHandler) GetPurchaseDraftAttachments(ctx context.Context, params GetPurchaseDraftAttachmentsParams) (r []Attachment, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPurchaseDrafts implements getPurchaseDrafts operation.
//
// Returns all purchase drafts for given company.
//
// GET /companies/{companySlug}/purchases/drafts
func (UnimplementedHandler) GetPurchaseDrafts(ctx context.Context, params GetPurchaseDraftsParams) (r *GetPurchaseDraftsOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPurchasePayment implements getPurchasePayment operation.
//
// Returns given payment for specified purchase.
//
// GET /companies/{companySlug}/purchases/{purchaseId}/payments/{paymentId}
func (UnimplementedHandler) GetPurchasePayment(ctx context.Context, params GetPurchasePaymentParams) (r *Payment, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPurchasePayments implements getPurchasePayments operation.
//
// Returns all purchases for given company.
//
// GET /companies/{companySlug}/purchases/{purchaseId}/payments
func (UnimplementedHandler) GetPurchasePayments(ctx context.Context, params GetPurchasePaymentsParams) (r []Payment, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPurchases implements getPurchases operation.
//
// Returns all purchases for given company.
//
// GET /companies/{companySlug}/purchases
func (UnimplementedHandler) GetPurchases(ctx context.Context, params GetPurchasesParams) (r *GetPurchasesOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSale implements getSale operation.
//
// Returns sale with specified id.
//
// GET /companies/{companySlug}/sales/{saleId}
func (UnimplementedHandler) GetSale(ctx context.Context, params GetSaleParams) (r *SaleResult, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSaleAttachments implements getSaleAttachments operation.
//
// Returns all attachments for specified sale.
//
// GET /companies/{companySlug}/sales/{saleId}/attachments
func (UnimplementedHandler) GetSaleAttachments(ctx context.Context, params GetSaleAttachmentsParams) (r []Attachment, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSaleDraft implements getSaleDraft operation.
//
// Returns draft with specified id.
//
// GET /companies/{companySlug}/sales/drafts/{draftId}
func (UnimplementedHandler) GetSaleDraft(ctx context.Context, params GetSaleDraftParams) (r *DraftResult, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSaleDraftAttachments implements getSaleDraftAttachments operation.
//
// Returns all attachments for specified draft.
//
// GET /companies/{companySlug}/sales/drafts/{draftId}/attachments
func (UnimplementedHandler) GetSaleDraftAttachments(ctx context.Context, params GetSaleDraftAttachmentsParams) (r []Attachment, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSaleDrafts implements getSaleDrafts operation.
//
// Returns all sale drafts for given company.
//
// GET /companies/{companySlug}/sales/drafts
func (UnimplementedHandler) GetSaleDrafts(ctx context.Context, params GetSaleDraftsParams) (r *GetSaleDraftsOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSalePayment implements getSalePayment operation.
//
// Returns payment with specified id.
//
// GET /companies/{companySlug}/sales/{saleId}/payments/{paymentId}
func (UnimplementedHandler) GetSalePayment(ctx context.Context, params GetSalePaymentParams) (r *Payment, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSalePayments implements getSalePayments operation.
//
// Returns all payments for given sale.
//
// GET /companies/{companySlug}/sales/{saleId}/payments
func (UnimplementedHandler) GetSalePayments(ctx context.Context, params GetSalePaymentsParams) (r []Payment, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSales implements getSales operation.
//
// Returns all sales for given company.
//
// GET /companies/{companySlug}/sales
func (UnimplementedHandler) GetSales(ctx context.Context, params GetSalesParams) (r *GetSalesOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTimeEntries implements getTimeEntries operation.
//
// Returns all time entries for given company.
//
// GET /companies/{companySlug}/timeEntries
func (UnimplementedHandler) GetTimeEntries(ctx context.Context, params GetTimeEntriesParams) (r *GetTimeEntriesOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTimeEntry implements getTimeEntry operation.
//
// Returns time entry with specified id.
//
// GET /companies/{companySlug}/timeEntries/{timeEntryId}
func (UnimplementedHandler) GetTimeEntry(ctx context.Context, params GetTimeEntryParams) (r *TimeEntryResult, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTimeUser implements getTimeUser operation.
//
// Returns time user with specified id.
//
// GET /companies/{companySlug}/timeUsers/{timeUserId}
func (UnimplementedHandler) GetTimeUser(ctx context.Context, params GetTimeUserParams) (r *TimeUserResult, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTimeUsers implements getTimeUsers operation.
//
// Returns all persons who can register time entries for the given company.
//
// GET /companies/{companySlug}/timeUsers
func (UnimplementedHandler) GetTimeUsers(ctx context.Context, params GetTimeUsersParams) (r *GetTimeUsersOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTransaction implements getTransaction operation.
//
// Returns given transaction with associated id. Transaction id is returned in GET calls for sales,
// purchases, and journal entries.
//
// GET /companies/{companySlug}/transactions/{transactionId}
func (UnimplementedHandler) GetTransaction(ctx context.Context, params GetTransactionParams) (r *Transaction, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTransactions implements getTransactions operation.
//
// Returns all transactions for the specified company.
//
// GET /companies/{companySlug}/transactions
func (UnimplementedHandler) GetTransactions(ctx context.Context, params GetTransactionsParams) (r *GetTransactionsOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUser implements getUser operation.
//
// Returns information about the user.
//
// GET /user
func (UnimplementedHandler) GetUser(ctx context.Context) (r *Userinfo, _ error) {
	return r, ht.ErrNotImplemented
}

// SendCreditNote implements sendCreditNote operation.
//
// Sends the specified document.
//
// POST /companies/{companySlug}/creditNotes/send
func (UnimplementedHandler) SendCreditNote(ctx context.Context, req *SendCreditNoteRequest, params SendCreditNoteParams) error {
	return ht.ErrNotImplemented
}

// SendInvoice implements sendInvoice operation.
//
// Sends the specified document.
//
// POST /companies/{companySlug}/invoices/send
func (UnimplementedHandler) SendInvoice(ctx context.Context, req *SendInvoiceRequest, params SendInvoiceParams) error {
	return ht.ErrNotImplemented
}

// SendOffer implements sendOffer operation.
//
// Sends the specified document.
//
// POST /companies/{companySlug}/offers/send
func (UnimplementedHandler) SendOffer(ctx context.Context, req *SendOfferRequest, params SendOfferParams) error {
	return ht.ErrNotImplemented
}

// SettledSale implements settledSale operation.
//
// Marks the sale as settled without payment. This is synonymous with "sett til oppgjort uten betaling"
// in the GUI. It is possible to change the date of settlement by sending a new settledDate.
//
// PATCH /companies/{companySlug}/sales/{saleId}/settled
func (UnimplementedHandler) SettledSale(ctx context.Context, params SettledSaleParams) (r *SaleResult, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateActivity implements updateActivity operation.
//
// Partially updates activity with provided id. Only provided fields will be updated.
//
// PATCH /companies/{companySlug}/activities/{activityId}
func (UnimplementedHandler) UpdateActivity(ctx context.Context, req *UpdateActivityRequest, params UpdateActivityParams) (r *UpdateActivityOK, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateContact implements updateContact operation.
//
// Updates an existing contact.
//
// PUT /companies/{companySlug}/contacts/{contactId}
func (UnimplementedHandler) UpdateContact(ctx context.Context, req *Contact, params UpdateContactParams) (r *UpdateContactOK, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateContactContactPerson implements updateContactContactPerson operation.
//
// Updates an existing contact person.
//
// PUT /companies/{companySlug}/contacts/{contactId}/contactPerson/{contactPersonId}
func (UnimplementedHandler) UpdateContactContactPerson(ctx context.Context, req *ContactPerson, params UpdateContactContactPersonParams) (r *UpdateContactContactPersonOK, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateCreditNoteDraft implements updateCreditNoteDraft operation.
//
// Updates credit note draft with provided id.
//
// PUT /companies/{companySlug}/creditNotes/drafts/{draftId}
func (UnimplementedHandler) UpdateCreditNoteDraft(ctx context.Context, req *InvoiceishDraftRequest, params UpdateCreditNoteDraftParams) (r *UpdateCreditNoteDraftCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateInvoice implements updateInvoice operation.
//
// Updates invoice with provided id. It is possible to update the due date of an invoice as well as if
// the invoice was sent manually, outside of Fiken.
//
// PATCH /companies/{companySlug}/invoices/{invoiceId}
func (UnimplementedHandler) UpdateInvoice(ctx context.Context, req *UpdateInvoiceRequest, params UpdateInvoiceParams) (r *UpdateInvoiceOK, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateInvoiceDraft implements updateInvoiceDraft operation.
//
// Updates invoice draft with provided id.
//
// PUT /companies/{companySlug}/invoices/drafts/{draftId}
func (UnimplementedHandler) UpdateInvoiceDraft(ctx context.Context, req *InvoiceishDraftRequest, params UpdateInvoiceDraftParams) (r *UpdateInvoiceDraftCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateOfferDraft implements updateOfferDraft operation.
//
// Updates offer draft with provided id.
//
// PUT /companies/{companySlug}/offers/drafts/{draftId}
func (UnimplementedHandler) UpdateOfferDraft(ctx context.Context, req *InvoiceishDraftRequest, params UpdateOfferDraftParams) (r *UpdateOfferDraftCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateOrderConfirmationDraft implements updateOrderConfirmationDraft operation.
//
// Updates order confirmation draft with provided id.
//
// PUT /companies/{companySlug}/orderConfirmations/drafts/{draftId}
func (UnimplementedHandler) UpdateOrderConfirmationDraft(ctx context.Context, req *InvoiceishDraftRequest, params UpdateOrderConfirmationDraftParams) (r *UpdateOrderConfirmationDraftCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateProduct implements updateProduct operation.
//
// Updates an existing product.
//
// PUT /companies/{companySlug}/products/{productId}
func (UnimplementedHandler) UpdateProduct(ctx context.Context, req *Product, params UpdateProductParams) (r *UpdateProductOK, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateProject implements updateProject operation.
//
// Updates project with provided id.
//
// PATCH /companies/{companySlug}/projects/{projectId}
func (UnimplementedHandler) UpdateProject(ctx context.Context, req *UpdateProjectRequest, params UpdateProjectParams) (r *UpdateProjectCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdatePurchaseDraft implements updatePurchaseDraft operation.
//
// Updates draft with provided id.
//
// PUT /companies/{companySlug}/purchases/drafts/{draftId}
func (UnimplementedHandler) UpdatePurchaseDraft(ctx context.Context, req *DraftRequest, params UpdatePurchaseDraftParams) (r *UpdatePurchaseDraftCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateSaleDraft implements updateSaleDraft operation.
//
// Updates draft with provided id.
//
// PUT /companies/{companySlug}/sales/drafts/{draftId}
func (UnimplementedHandler) UpdateSaleDraft(ctx context.Context, req *DraftRequest, params UpdateSaleDraftParams) (r *UpdateSaleDraftCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTimeEntry implements updateTimeEntry operation.
//
// Partially updates time entry with provided id. Only provided fields will be updated.
//
// PATCH /companies/{companySlug}/timeEntries/{timeEntryId}
func (UnimplementedHandler) UpdateTimeEntry(ctx context.Context, req *UpdateTimeEntryRequest, params UpdateTimeEntryParams) (r *UpdateTimeEntryOK, _ error) {
	return r, ht.ErrNotImplemented
}

// WriteOffSale implements writeOffSale operation.
//
// Registers a write-off (tapsføring) for the given sale. The sale must not be a cash sale, must not
// already be written off, settled, or deleted, and must have an outstanding balance. The write-off
// date must be after the sale date.
//
// PATCH /companies/{companySlug}/sales/{saleId}/writeOff
func (UnimplementedHandler) WriteOffSale(ctx context.Context, req *WriteOffRequest, params WriteOffSaleParams) (r *SaleResult, _ error) {
	return r, ht.ErrNotImplemented
}
