// Code generated by ogen, DO NOT EDIT.

package fiken

// setDefaults set default value of fields.
func (s *BankAccountRequest) setDefaults() {
	{
		val := bool(false)
		s.Inactive.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BankAccountResult) setDefaults() {
	{
		val := bool(false)
		s.Inactive.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *Contact) setDefaults() {
	{
		val := bool(false)
		s.Customer.SetTo(val)
	}
	{
		val := bool(false)
		s.Supplier.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *Counter) setDefaults() {
	{
		val := int32(10000)
		s.Value.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GeneralJournalEntryRequest) setDefaults() {
	{
		val := bool(false)
		s.Open.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *InvoiceResult) setDefaults() {
	{
		val := string("NOK")
		s.Currency.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *InvoiceishDraftResult) setDefaults() {
	{
		val := InvoiceishDraftResultType("invoice")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *Offer) setDefaults() {
	{
		val := string("NOK")
		s.Currency.SetTo(val)
	}
	{
		val := bool(false)
		s.Archived.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *OrderConfirmation) setDefaults() {
	{
		val := string("NOK")
		s.Currency.SetTo(val)
	}
	{
		val := bool(false)
		s.Archived.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *Product) setDefaults() {
	{
		val := bool(true)
		s.Active = val
	}
}

// setDefaults set default value of fields.
func (s *SendCreditNoteRequest) setDefaults() {
	{
		val := bool(true)
		s.IncludeDocumentAttachments = val
	}
	{
		val := SendCreditNoteRequestEmailSendOption("auto")
		s.EmailSendOption.SetTo(val)
	}
	{
		val := bool(false)
		s.MergeInvoiceAndAttachments.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SendInvoiceRequest) setDefaults() {
	{
		val := bool(true)
		s.IncludeDocumentAttachments = val
	}
	{
		val := SendInvoiceRequestEmailSendOption("auto")
		s.EmailSendOption.SetTo(val)
	}
	{
		val := bool(false)
		s.MergeInvoiceAndAttachments.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SendOfferRequest) setDefaults() {
	{
		val := bool(true)
		s.IncludeDocumentAttachments = val
	}
	{
		val := SendOfferRequestEmailSendOption("auto")
		s.EmailSendOption.SetTo(val)
	}
	{
		val := bool(false)
		s.MergeInvoiceAndAttachments.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TimeEntryInvoiceDraftRequest) setDefaults() {
	{
		val := TimeEntryInvoiceDraftRequestGroupBy("activity")
		s.GroupBy.SetTo(val)
	}
	{
		val := bool(false)
		s.IncludeTimeEntryDescriptions.SetTo(val)
	}
	{
		val := string("NOK")
		s.Currency.SetTo(val)
	}
}
