// Code generated by ogen, DO NOT EDIT.

package fiken

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleFikenAPIOAuth handles fiken_api_oauth security.
	HandleFikenAPIOAuth(ctx context.Context, operationName OperationName, t FikenAPIOAuth) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// oauth2ScopesFikenAPIOAuth is a private map storing OAuth2 scopes per operation.
var oauth2ScopesFikenAPIOAuth = map[string][]string{
	AddAttachmentToContactOperation:                  []string{},
	AddAttachmentToCreditNoteDraftOperation:          []string{},
	AddAttachmentToInvoiceOperation:                  []string{},
	AddAttachmentToInvoiceDraftOperation:             []string{},
	AddAttachmentToJournalEntryOperation:             []string{},
	AddAttachmentToOfferDraftOperation:               []string{},
	AddAttachmentToOrderConfirmationDraftOperation:   []string{},
	AddAttachmentToPurchaseOperation:                 []string{},
	AddAttachmentToPurchaseDraftOperation:            []string{},
	AddAttachmentToSaleOperation:                     []string{},
	AddAttachmentToSaleDraftOperation:                []string{},
	AddContactPersonToContactOperation:               []string{},
	CreateActivityOperation:                          []string{},
	CreateBankAccountOperation:                       []string{},
	CreateContactOperation:                           []string{},
	CreateCreditNoteCounterOperation:                 []string{},
	CreateCreditNoteDraftOperation:                   []string{},
	CreateCreditNoteFromDraftOperation:               []string{},
	CreateFullCreditNoteOperation:                    []string{},
	CreateGeneralJournalEntryOperation:               []string{},
	CreateInboxDocumentOperation:                     []string{},
	CreateInvoiceOperation:                           []string{},
	CreateInvoiceCounterOperation:                    []string{},
	CreateInvoiceDraftOperation:                      []string{},
	CreateInvoiceDraftFromOrderConfirmationOperation: []string{},
	CreateInvoiceDraftFromTimeEntriesOperation:       []string{},
	CreateInvoiceFromDraftOperation:                  []string{},
	CreateOfferCounterOperation:                      []string{},
	CreateOfferDraftOperation:                        []string{},
	CreateOfferFromDraftOperation:                    []string{},
	CreateOrderConfirmationCounterOperation:          []string{},
	CreateOrderConfirmationDraftOperation:            []string{},
	CreateOrderConfirmationFromDraftOperation:        []string{},
	CreatePartialCreditNoteOperation:                 []string{},
	CreateProductOperation:                           []string{},
	CreateProductSalesReportOperation:                []string{},
	CreateProjectOperation:                           []string{},
	CreatePurchaseOperation:                          []string{},
	CreatePurchaseDraftOperation:                     []string{},
	CreatePurchaseFromDraftOperation:                 []string{},
	CreatePurchasePaymentOperation:                   []string{},
	CreateSaleOperation:                              []string{},
	CreateSaleDraftOperation:                         []string{},
	CreateSaleFromDraftOperation:                     []string{},
	CreateSalePaymentOperation:                       []string{},
	CreateTimeEntryOperation:                         []string{},
	DeleteActivityOperation:                          []string{},
	DeleteContactOperation:                           []string{},
	DeleteContactContactPersonOperation:              []string{},
	DeleteCreditNoteDraftOperation:                   []string{},
	DeleteInvoiceDraftOperation:                      []string{},
	DeleteOfferDraftOperation:                        []string{},
	DeleteOrderConfirmationDraftOperation:            []string{},
	DeleteProductOperation:                           []string{},
	DeleteProjectOperation:                           []string{},
	DeletePurchaseOperation:                          []string{},
	DeletePurchaseDraftOperation:                     []string{},
	DeleteSaleOperation:                              []string{},
	DeleteSaleDraftOperation:                         []string{},
	DeleteTimeEntryOperation:                         []string{},
	DeleteTransactionOperation:                       []string{},
	GetAccountOperation:                              []string{},
	GetAccountBalanceOperation:                       []string{},
	GetAccountBalancesOperation:                      []string{},
	GetAccountsOperation:                             []string{},
	GetActivitiesOperation:                           []string{},
	GetActivityOperation:                             []string{},
	GetBankAccountOperation:                          []string{},
	GetBankAccountsOperation:                         []string{},
	GetBankBalancesOperation:                         []string{},
	GetCompaniesOperation:                            []string{},
	GetCompanyOperation:                              []string{},
	GetContactOperation:                              []string{},
	GetContactContactPersonOperation:                 []string{},
	GetContactPersonOperation:                        []string{},
	GetContactsOperation:                             []string{},
	GetCreditNoteOperation:                           []string{},
	GetCreditNoteCounterOperation:                    []string{},
	GetCreditNoteDraftOperation:                      []string{},
	GetCreditNoteDraftAttachmentsOperation:           []string{},
	GetCreditNoteDraftsOperation:                     []string{},
	GetCreditNotesOperation:                          []string{},
	GetGroupsOperation:                               []string{},
	GetInboxOperation:                                []string{},
	GetInboxDocumentOperation:                        []string{},
	GetInvoiceOperation:                              []string{},
	GetInvoiceAttachmentsOperation:                   []string{},
	GetInvoiceCounterOperation:                       []string{},
	GetInvoiceDraftOperation:                         []string{},
	GetInvoiceDraftAttachmentsOperation:              []string{},
	GetInvoiceDraftsOperation:                        []string{},
	GetInvoicesOperation:                             []string{},
	GetJournalEntriesOperation:                       []string{},
	GetJournalEntryOperation:                         []string{},
	GetJournalEntryAttachmentsOperation:              []string{},
	GetOfferOperation:                                []string{},
	GetOfferCounterOperation:                         []string{},
	GetOfferDraftOperation:                           []string{},
	GetOfferDraftAttachmentsOperation:                []string{},
	GetOfferDraftsOperation:                          []string{},
	GetOffersOperation:                               []string{},
	GetOrderConfirmationOperation:                    []string{},
	GetOrderConfirmationCounterOperation:             []string{},
	GetOrderConfirmationDraftOperation:               []string{},
	GetOrderConfirmationDraftAttachmentsOperation:    []string{},
	GetOrderConfirmationDraftsOperation:              []string{},
	GetOrderConfirmationsOperation:                   []string{},
	GetProductOperation:                              []string{},
	GetProductsOperation:                             []string{},
	GetProjectOperation:                              []string{},
	GetProjectsOperation:                             []string{},
	GetPurchaseOperation:                             []string{},
	GetPurchaseAttachmentsOperation:                  []string{},
	GetPurchaseDraftOperation:                        []string{},
	GetPurchaseDraftAttachmentsOperation:             []string{},
	GetPurchaseDraftsOperation:                       []string{},
	GetPurchasePaymentOperation:                      []string{},
	GetPurchasePaymentsOperation:                     []string{},
	GetPurchasesOperation:                            []string{},
	GetSaleOperation:                                 []string{},
	GetSaleAttachmentsOperation:                      []string{},
	GetSaleDraftOperation:                            []string{},
	GetSaleDraftAttachmentsOperation:                 []string{},
	GetSaleDraftsOperation:                           []string{},
	GetSalePaymentOperation:                          []string{},
	GetSalePaymentsOperation:                         []string{},
	GetSalesOperation:                                []string{},
	GetTimeEntriesOperation:                          []string{},
	GetTimeEntryOperation:                            []string{},
	GetTimeUserOperation:                             []string{},
	GetTimeUsersOperation:                            []string{},
	GetTransactionOperation:                          []string{},
	GetTransactionsOperation:                         []string{},
	GetUserOperation:                                 []string{},
	SendCreditNoteOperation:                          []string{},
	SendInvoiceOperation:                             []string{},
	SendOfferOperation:                               []string{},
	SettledSaleOperation:                             []string{},
	UpdateActivityOperation:                          []string{},
	UpdateContactOperation:                           []string{},
	UpdateContactContactPersonOperation:              []string{},
	UpdateCreditNoteDraftOperation:                   []string{},
	UpdateInvoiceOperation:                           []string{},
	UpdateInvoiceDraftOperation:                      []string{},
	UpdateOfferDraftOperation:                        []string{},
	UpdateOrderConfirmationDraftOperation:            []string{},
	UpdateProductOperation:                           []string{},
	UpdateProjectOperation:                           []string{},
	UpdatePurchaseDraftOperation:                     []string{},
	UpdateSaleDraftOperation:                         []string{},
	UpdateTimeEntryOperation:                         []string{},
	WriteOffSaleOperation:                            []string{},
}

// GetOAuth2ScopesForFikenAPIOAuth returns the required OAuth2 scopes for the given operation.
//
// This is useful for token exchange scenarios where you need to know which scopes
// to request when obtaining a token for a downstream API call.
//
// Example:
//
//	requiredScopes := GetOAuth2ScopesForFikenAPIOAuth(AddPetOperation)
//	token := exchangeTokenWithScopes(requiredScopes, "https://api.example.com")
//
// Returns nil if the operation has no scope requirements or if the operation is unknown.
func GetOAuth2ScopesForFikenAPIOAuth(operation string) []string {
	scopes, ok := oauth2ScopesFikenAPIOAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(scopes))
	copy(result, scopes)
	return result
}

func (s *Server) securityFikenAPIOAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t FikenAPIOAuth
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Scopes = oauth2ScopesFikenAPIOAuth[operationName]
	rctx, err := s.sec.HandleFikenAPIOAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// FikenAPIOAuth provides fiken_api_oauth security value.
	FikenAPIOAuth(ctx context.Context, operationName OperationName) (FikenAPIOAuth, error)
}

func (s *Client) securityFikenAPIOAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.FikenAPIOAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"FikenAPIOAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
