// Package i18n holds the runtime translation bundle and locale TOML
// catalogs. `i18n/locales/en.template.toml` is editor scaffolding
// generated by cmd/fiken-i18n-scaffold from the OAS spec and is NOT
// loaded at runtime.
package i18n

//go:generate go run ../cmd/fiken-i18n-scaffold -spec ../api/fiken-openapi.yaml -out locales/en.template.toml
