// Command fiken-i18n-scaffold reads api/fiken-openapi.yaml and emits
// i18n/locales/en.template.toml: an editor scaffold with one stanza
// per operation, pre-filled with a `summary` derived from the spec's
// `description` field (or `summary` if present), and empty
// `when_to_use`, `returns`, `example` keys for the author to fill.
//
// The generated file is NOT loaded by the runtime i18n bundle.
// Authors copy or rewrite entries into `i18n/locales/en.toml`.
package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	defaultSpec   = "api/fiken-openapi.yaml"
	defaultOutput = "i18n/locales/en.template.toml"
)

// httpMethods is the whitelist of OAS path-item keys that name an
// operation. Other keys (parameters, description, servers, summary,
// etc.) are skipped by parseEntries.
var httpMethods = map[string]bool{
	"get":     true,
	"put":     true,
	"post":    true,
	"delete":  true,
	"options": true,
	"head":    true,
	"patch":   true,
	"trace":   true,
}

func main() {
	specPath := flag.String("spec", defaultSpec, "path to OAS YAML")
	outPath := flag.String("out", defaultOutput, "output file")
	flag.Parse()

	if err := run(*specPath, *outPath); err != nil {
		fmt.Fprintf(os.Stderr, "fiken-i18n-scaffold: %v\n", err)
		os.Exit(1)
	}
}

func run(specPath, outPath string) error {
	data, err := os.ReadFile(specPath)
	if err != nil {
		return err
	}
	entries, err := parseEntries(data)
	if err != nil {
		return err
	}

	if err := os.MkdirAll(parentDir(outPath), 0o755); err != nil {
		return err
	}
	f, err := os.Create(outPath)
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintln(f, "# Code generated by fiken-i18n-scaffold; not loaded at runtime.")
	fmt.Fprintln(f, "# Copy or rewrite entries from here into en.toml. Edit freely.")
	fmt.Fprintln(f, "")

	keys := make([]string, 0, len(entries))
	for k := range entries {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for i, k := range keys {
		stanza := renderEntry(k, entries[k])
		// Last stanza: drop the trailing blank-line separator so the
		// file ends with a single newline (end-of-file-fixer rule).
		if i == len(keys)-1 {
			stanza = strings.TrimRight(stanza, "\n") + "\n"
		}
		fmt.Fprint(f, stanza)
	}
	return nil
}

// parseEntries walks paths.*.{method}.{summary,description,operationId}
// and returns a map of snake_case opId → starter text. The starter
// text prefers `summary` over `description` because summary is
// already one-liner shaped; falls back to truncated description.
func parseEntries(specYAML []byte) (map[string]string, error) {
	var root struct {
		Paths map[string]map[string]yaml.Node `yaml:"paths"`
	}
	if err := yaml.Unmarshal(specYAML, &root); err != nil {
		return nil, err
	}
	out := make(map[string]string, 128)
	for _, pathItem := range root.Paths {
		for method, node := range pathItem {
			if !httpMethods[strings.ToLower(method)] {
				continue
			}
			var op struct {
				OperationID string `yaml:"operationId"`
				Summary     string `yaml:"summary"`
				Description string `yaml:"description"`
			}
			if err := node.Decode(&op); err != nil {
				continue
			}
			if op.OperationID == "" {
				continue
			}
			src := op.Summary
			if src == "" {
				src = op.Description
			}
			out[snake(op.OperationID)] = truncateDesc(src)
		}
	}
	return out, nil
}

func renderEntry(op, desc string) string {
	pad := func(s string) string {
		const want = 11
		return s + strings.Repeat(" ", want-len(s))
	}
	return fmt.Sprintf(
		"[ops.%s]\n"+
			"%s = %s\n"+
			"%s = \"\"\n"+
			"%s = \"\"\n"+
			"%s = \"\"\n"+
			"\n",
		op,
		pad("summary"), tomlString(desc),
		pad("when_to_use"),
		pad("returns"),
		pad("example"),
	)
}

func tomlString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

func truncateDesc(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return ""
	}
	if idx := strings.Index(s, "."); idx >= 0 && idx < 200 {
		return s[:idx+1]
	}
	if len(s) > 200 {
		return s[:200] + "…"
	}
	return s
}

func snake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			b.WriteByte('_')
		}
		if r >= 'A' && r <= 'Z' {
			r += 'a' - 'A'
		}
		b.WriteRune(r)
	}
	return b.String()
}

func parentDir(p string) string {
	for i := len(p) - 1; i >= 0; i-- {
		if p[i] == '/' {
			return p[:i]
		}
	}
	return "."
}
